// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/surfacers/stackdriver/proto/config.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SurfacerConf struct {
	// This field doesn't do anything anymore. Batching is always enabled. This
	// field will be removed after release v0.10.3.
	Batch *bool `protobuf:"varint,1,opt,name=batch,def=1" json:"batch,omitempty"`
	// This field doesn't do anything anymore. Batch size is always 200. This
	// field will be removed after release v0.10.3.
	BatchSize *uint64 `protobuf:"varint,2,opt,name=batch_size,json=batchSize,def=200" json:"batch_size,omitempty"`
	// How often to export metrics to stackdriver.
	BatchTimerSec *uint64 `protobuf:"varint,3,opt,name=batch_timer_sec,json=batchTimerSec,def=10" json:"batch_timer_sec,omitempty"`
	// If allowed_metrics_regex is specified, only metrics matching the given
	// regular expression will be exported to stackdriver. Since probe type and
	// probe name are part of the metric name, you can use this field to restrict
	// stackdriver metrics to a particular probe.
	// Example:
	// allowed_metrics_regex: ".*(http|ping).*(success|validation_failure).*"
	AllowedMetricsRegex *string `protobuf:"bytes,4,opt,name=allowed_metrics_regex,json=allowedMetricsRegex" json:"allowed_metrics_regex,omitempty"`
	// Monitoring URL base. Full metric URL looks like the following:
	// <monitoring_url>/<ptype>/<probe>/<metric>
	// Example:
	// custom.googleapis.com/cloudprober/http/google-homepage/latency
	MonitoringUrl        *string  `protobuf:"bytes,5,opt,name=monitoring_url,json=monitoringUrl,def=custom.googleapis.com/cloudprober/" json:"monitoring_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurfacerConf) Reset()         { *m = SurfacerConf{} }
func (m *SurfacerConf) String() string { return proto.CompactTextString(m) }
func (*SurfacerConf) ProtoMessage()    {}
func (*SurfacerConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_7b0050a462f143bb, []int{0}
}
func (m *SurfacerConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurfacerConf.Unmarshal(m, b)
}
func (m *SurfacerConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurfacerConf.Marshal(b, m, deterministic)
}
func (dst *SurfacerConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurfacerConf.Merge(dst, src)
}
func (m *SurfacerConf) XXX_Size() int {
	return xxx_messageInfo_SurfacerConf.Size(m)
}
func (m *SurfacerConf) XXX_DiscardUnknown() {
	xxx_messageInfo_SurfacerConf.DiscardUnknown(m)
}

var xxx_messageInfo_SurfacerConf proto.InternalMessageInfo

const Default_SurfacerConf_Batch bool = true
const Default_SurfacerConf_BatchSize uint64 = 200
const Default_SurfacerConf_BatchTimerSec uint64 = 10
const Default_SurfacerConf_MonitoringUrl string = "custom.googleapis.com/cloudprober/"

func (m *SurfacerConf) GetBatch() bool {
	if m != nil && m.Batch != nil {
		return *m.Batch
	}
	return Default_SurfacerConf_Batch
}

func (m *SurfacerConf) GetBatchSize() uint64 {
	if m != nil && m.BatchSize != nil {
		return *m.BatchSize
	}
	return Default_SurfacerConf_BatchSize
}

func (m *SurfacerConf) GetBatchTimerSec() uint64 {
	if m != nil && m.BatchTimerSec != nil {
		return *m.BatchTimerSec
	}
	return Default_SurfacerConf_BatchTimerSec
}

func (m *SurfacerConf) GetAllowedMetricsRegex() string {
	if m != nil && m.AllowedMetricsRegex != nil {
		return *m.AllowedMetricsRegex
	}
	return ""
}

func (m *SurfacerConf) GetMonitoringUrl() string {
	if m != nil && m.MonitoringUrl != nil {
		return *m.MonitoringUrl
	}
	return Default_SurfacerConf_MonitoringUrl
}

func init() {
	proto.RegisterType((*SurfacerConf)(nil), "cloudprober.surfacer.stackdriver.SurfacerConf")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/surfacers/stackdriver/proto/config.proto", fileDescriptor_config_7b0050a462f143bb)
}

var fileDescriptor_config_7b0050a462f143bb = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbf, 0x6b, 0xf3, 0x30,
	0x10, 0x86, 0x71, 0x7e, 0xc0, 0x17, 0xf1, 0xa5, 0x05, 0x95, 0x82, 0xe9, 0x64, 0x32, 0x85, 0x0e,
	0x56, 0x9a, 0x31, 0x6b, 0xa1, 0xd0, 0xa1, 0x8b, 0xd2, 0xce, 0xc6, 0x96, 0xcf, 0x8a, 0xa8, 0xec,
	0x33, 0x27, 0xa9, 0x2d, 0xf9, 0xcf, 0xbb, 0x15, 0xcb, 0x29, 0xf5, 0x76, 0xf7, 0x3e, 0xef, 0xb3,
	0xbc, 0xec, 0x49, 0x1b, 0x7f, 0x0a, 0x55, 0xae, 0xb0, 0x15, 0x1a, 0x51, 0x5b, 0x10, 0xca, 0x62,
	0xa8, 0x7b, 0xc2, 0x0a, 0x48, 0xb8, 0x40, 0x4d, 0xa9, 0x80, 0x9c, 0x70, 0xbe, 0x54, 0xef, 0x35,
	0x99, 0x0f, 0x20, 0xd1, 0x13, 0x7a, 0x14, 0x0a, 0xbb, 0xc6, 0xe8, 0x3c, 0x3e, 0x3c, 0x9b, 0x58,
	0xf9, 0xaf, 0x95, 0x4f, 0xa4, 0xcd, 0x77, 0xc2, 0xfe, 0x1f, 0x2f, 0xe0, 0x11, 0xbb, 0x86, 0xdf,
	0xb1, 0x65, 0x55, 0x7a, 0x75, 0x4a, 0x93, 0x2c, 0xd9, 0xfe, 0x3b, 0x2c, 0x3c, 0x05, 0x90, 0x63,
	0xc4, 0x37, 0x8c, 0xc5, 0xa3, 0x70, 0xe6, 0x0c, 0xe9, 0x2c, 0x4b, 0xb6, 0x8b, 0xc3, 0x7c, 0xbf,
	0xdb, 0xc9, 0x55, 0x8c, 0x8f, 0xe6, 0x0c, 0xfc, 0x9e, 0x5d, 0x8f, 0x1d, 0x6f, 0x5a, 0xa0, 0xc2,
	0x81, 0x4a, 0xe7, 0xb1, 0x38, 0x7b, 0xd8, 0xc9, 0x75, 0x44, 0xaf, 0x03, 0x39, 0x82, 0xe2, 0x7b,
	0x76, 0x5b, 0x5a, 0x8b, 0x9f, 0x50, 0x17, 0x2d, 0x78, 0x32, 0xca, 0x15, 0x04, 0x1a, 0xbe, 0xd2,
	0x45, 0x96, 0x6c, 0x57, 0xf2, 0xe6, 0x02, 0x5f, 0x46, 0x26, 0x07, 0xc4, 0x9f, 0xd9, 0x55, 0x8b,
	0x9d, 0xf1, 0x48, 0xa6, 0xd3, 0x45, 0x20, 0x9b, 0x2e, 0x87, 0xf2, 0x61, 0xa3, 0x82, 0xf3, 0xd8,
	0xe6, 0xe3, 0x5c, 0x65, 0x6f, 0x5c, 0x5c, 0x6f, 0x3a, 0x9b, 0x5c, 0xff, 0x99, 0x6f, 0x64, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xdc, 0xb6, 0x3d, 0x66, 0x01, 0x00, 0x00,
}
