// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/probes/udp/config.proto

/*
Package udp is a generated protocol buffer package.

It is generated from these files:
	github.com/google/cloudprober/probes/udp/config.proto

It has these top-level messages:
	ProbeConf
*/
package udp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProbeConf struct {
	// Export stats after these many milliseconds
	StatsExportIntervalMsec *int32 `protobuf:"varint,2,opt,name=stats_export_interval_msec,json=statsExportIntervalMsec,def=10000" json:"stats_export_interval_msec,omitempty"`
	// Port to send UDP Ping to (UDP Echo).  Should be same as
	// ProberConfig.udp_echo_server_port.
	// TODO: Can we just read this from ProberConfig?
	Port *int32 `protobuf:"varint,3,opt,name=port,def=31122" json:"port,omitempty"`
	// Number of sending side ports to use.
	NumTxPorts *int32 `protobuf:"varint,4,opt,name=num_tx_ports,json=numTxPorts,def=16" json:"num_tx_ports,omitempty"`
	// message max to account for MTU.
	MaxLength *int32 `protobuf:"varint,5,opt,name=max_length,json=maxLength,def=1300" json:"max_length,omitempty"`
	// IP proto: v4|v6. Temporary workaround till we add support in base probe proto.
	IpVersion        *int32 `protobuf:"varint,6,opt,name=ip_version,json=ipVersion,def=4" json:"ip_version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProbeConf) Reset()                    { *m = ProbeConf{} }
func (m *ProbeConf) String() string            { return proto.CompactTextString(m) }
func (*ProbeConf) ProtoMessage()               {}
func (*ProbeConf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_ProbeConf_StatsExportIntervalMsec int32 = 10000
const Default_ProbeConf_Port int32 = 31122
const Default_ProbeConf_NumTxPorts int32 = 16
const Default_ProbeConf_MaxLength int32 = 1300
const Default_ProbeConf_IpVersion int32 = 4

func (m *ProbeConf) GetStatsExportIntervalMsec() int32 {
	if m != nil && m.StatsExportIntervalMsec != nil {
		return *m.StatsExportIntervalMsec
	}
	return Default_ProbeConf_StatsExportIntervalMsec
}

func (m *ProbeConf) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return Default_ProbeConf_Port
}

func (m *ProbeConf) GetNumTxPorts() int32 {
	if m != nil && m.NumTxPorts != nil {
		return *m.NumTxPorts
	}
	return Default_ProbeConf_NumTxPorts
}

func (m *ProbeConf) GetMaxLength() int32 {
	if m != nil && m.MaxLength != nil {
		return *m.MaxLength
	}
	return Default_ProbeConf_MaxLength
}

func (m *ProbeConf) GetIpVersion() int32 {
	if m != nil && m.IpVersion != nil {
		return *m.IpVersion
	}
	return Default_ProbeConf_IpVersion
}

func init() {
	proto.RegisterType((*ProbeConf)(nil), "cloudprober.probes.udp.ProbeConf")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/probes/udp/config.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xca, 0x3f, 0x4b, 0xfc, 0x30,
	0x1c, 0xc7, 0x71, 0x7a, 0xbf, 0xf6, 0x07, 0xfd, 0xe2, 0x94, 0x41, 0xab, 0xd3, 0xa1, 0x0e, 0x4e,
	0x6d, 0x7a, 0xa7, 0x0e, 0x8e, 0x8a, 0x83, 0xa0, 0x70, 0x14, 0x71, 0x0d, 0xbd, 0x36, 0x97, 0x0b,
	0x34, 0xf9, 0x86, 0xfc, 0x39, 0xf2, 0x4c, 0x7d, 0x3a, 0xd2, 0xd4, 0xc1, 0xe9, 0xc3, 0xe7, 0xcd,
	0x0b, 0x1e, 0x84, 0xf4, 0xc7, 0xb0, 0xaf, 0x07, 0x54, 0x8d, 0x40, 0x14, 0x13, 0x6f, 0x86, 0x09,
	0xc3, 0x68, 0x2c, 0xee, 0xb9, 0x6d, 0xd2, 0xb8, 0x26, 0x8c, 0xa6, 0x19, 0x50, 0x1f, 0xa4, 0xa8,
	0x8d, 0x45, 0x8f, 0xe4, 0xfc, 0x0f, 0xaa, 0x17, 0x54, 0x87, 0xd1, 0x5c, 0x7f, 0x67, 0x50, 0xee,
	0xe6, 0xfb, 0x82, 0xfa, 0x40, 0x9e, 0xe1, 0xca, 0xf9, 0xde, 0x3b, 0xc6, 0xa3, 0x41, 0xeb, 0x99,
	0xd4, 0x9e, 0xdb, 0x53, 0x3f, 0x31, 0xe5, 0xf8, 0x50, 0xad, 0xd6, 0xd9, 0x5d, 0xf1, 0x54, 0xb4,
	0x94, 0x52, 0xda, 0x5d, 0x24, 0xf8, 0x9a, 0xdc, 0xdb, 0x2f, 0xfb, 0x70, 0x7c, 0x20, 0x97, 0x90,
	0xcf, 0xad, 0xfa, 0xb7, 0xe8, 0x6d, 0xdb, 0x6e, 0x36, 0x5d, 0x4a, 0xe4, 0x16, 0xce, 0x74, 0x50,
	0xcc, 0x47, 0x36, 0x5f, 0x57, 0xe5, 0x89, 0xac, 0xda, 0xc7, 0x0e, 0x74, 0x50, 0x9f, 0x71, 0x37,
	0x57, 0x72, 0x03, 0xa0, 0xfa, 0xc8, 0x26, 0xae, 0x85, 0x3f, 0x56, 0x45, 0x32, 0x79, 0xbb, 0xa5,
	0xb4, 0x2b, 0x55, 0x1f, 0xdf, 0x53, 0x26, 0x6b, 0x00, 0x69, 0xd8, 0x89, 0x5b, 0x27, 0x51, 0x57,
	0xff, 0x13, 0xca, 0xee, 0xbb, 0x52, 0x9a, 0xaf, 0xa5, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x72, 0x81, 0xc8, 0x29, 0x01, 0x00, 0x00,
}
