// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/validators/integrity/proto/config.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Validator struct {
	// Validate the data integrity of the response using a pattern that is
	// repeated throughout the length of the response, with last len(response) %
	// len(pattern) bytes being zero bytes.
	//
	// For example if response length is 100 bytes and pattern length is 8 bytes,
	// first 96 bytes of the response should be pattern repeated 12 times, and
	// last 4 bytes should be set to zero byte ('\0')
	//
	// Types that are valid to be assigned to Pattern:
	//	*Validator_PatternString
	//	*Validator_PatternNumBytes
	Pattern              isValidator_Pattern `protobuf_oneof:"pattern"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_ee43a05c25c7af91, []int{0}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (dst *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(dst, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

type isValidator_Pattern interface {
	isValidator_Pattern()
}

type Validator_PatternString struct {
	PatternString string `protobuf:"bytes,1,opt,name=pattern_string,json=patternString,oneof"`
}

type Validator_PatternNumBytes struct {
	PatternNumBytes int32 `protobuf:"varint,2,opt,name=pattern_num_bytes,json=patternNumBytes,oneof"`
}

func (*Validator_PatternString) isValidator_Pattern() {}

func (*Validator_PatternNumBytes) isValidator_Pattern() {}

func (m *Validator) GetPattern() isValidator_Pattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *Validator) GetPatternString() string {
	if x, ok := m.GetPattern().(*Validator_PatternString); ok {
		return x.PatternString
	}
	return ""
}

func (m *Validator) GetPatternNumBytes() int32 {
	if x, ok := m.GetPattern().(*Validator_PatternNumBytes); ok {
		return x.PatternNumBytes
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Validator) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Validator_OneofMarshaler, _Validator_OneofUnmarshaler, _Validator_OneofSizer, []interface{}{
		(*Validator_PatternString)(nil),
		(*Validator_PatternNumBytes)(nil),
	}
}

func _Validator_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Validator)
	// pattern
	switch x := m.Pattern.(type) {
	case *Validator_PatternString:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.PatternString)
	case *Validator_PatternNumBytes:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.PatternNumBytes))
	case nil:
	default:
		return fmt.Errorf("Validator.Pattern has unexpected type %T", x)
	}
	return nil
}

func _Validator_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Validator)
	switch tag {
	case 1: // pattern.pattern_string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Pattern = &Validator_PatternString{x}
		return true, err
	case 2: // pattern.pattern_num_bytes
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Pattern = &Validator_PatternNumBytes{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Validator_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Validator)
	// pattern
	switch x := m.Pattern.(type) {
	case *Validator_PatternString:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.PatternString)))
		n += len(x.PatternString)
	case *Validator_PatternNumBytes:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.PatternNumBytes))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Validator)(nil), "cloudprober.validators.integrity.Validator")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/validators/integrity/proto/config.proto", fileDescriptor_config_ee43a05c25c7af91)
}

var fileDescriptor_config_ee43a05c25c7af91 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcb, 0xcf, 0x0a, 0x82, 0x40,
	0x10, 0xc7, 0x71, 0x0d, 0x22, 0x5c, 0xa8, 0xc8, 0x93, 0x47, 0xe9, 0x92, 0x87, 0xd8, 0x7d, 0x07,
	0x21, 0xf0, 0xd4, 0xc1, 0xa0, 0xab, 0xf8, 0x67, 0xdb, 0x16, 0xdc, 0x1d, 0x19, 0x67, 0x03, 0xdf,
	0x3e, 0x92, 0xb5, 0x3a, 0xce, 0xe7, 0x37, 0x5f, 0x76, 0x51, 0x9a, 0x9e, 0xae, 0xe1, 0x2d, 0x18,
	0xa1, 0x00, 0x54, 0x2f, 0x45, 0xdb, 0x83, 0xeb, 0x06, 0x84, 0x46, 0xa2, 0x78, 0xd5, 0xbd, 0xee,
	0x6a, 0x02, 0x1c, 0x85, 0xb6, 0x24, 0x15, 0x6a, 0x9a, 0xc4, 0x80, 0x40, 0x20, 0x5a, 0xb0, 0x0f,
	0xad, 0xf8, 0x7c, 0xc4, 0xe9, 0x5f, 0xc4, 0x7f, 0x11, 0xff, 0x46, 0x47, 0xc3, 0xa2, 0xfb, 0xe2,
	0xf1, 0x89, 0xed, 0x86, 0x9a, 0x48, 0xa2, 0xad, 0x46, 0x42, 0x6d, 0x55, 0x12, 0xa6, 0x61, 0x16,
	0x15, 0x41, 0xb9, 0xf5, 0x7e, 0x9b, 0x39, 0x3e, 0xb3, 0xc3, 0xf2, 0x68, 0x9d, 0xa9, 0x9a, 0x89,
	0xe4, 0x98, 0xac, 0xd2, 0x30, 0x5b, 0x17, 0x41, 0xb9, 0xf7, 0xd3, 0xd5, 0x99, 0xfc, 0x33, 0xe4,
	0x11, 0xdb, 0x78, 0x7a, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xc4, 0x15, 0xf9, 0xd8, 0x00, 0x00,
	0x00,
}
