// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/targets/proto/targets.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/google/cloudprober/rds/proto"
	proto2 "github.com/google/cloudprober/targets/gce/proto"
	proto4 "github.com/google/cloudprober/targets/lameduck/proto"
	proto3 "github.com/google/cloudprober/targets/rtc/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RDSTargets struct {
	// RDS server address. If not specified, RDS server address from the global
	// options is used.
	RdsServerAddress *string `protobuf:"bytes,1,opt,name=rds_server_address,json=rdsServerAddress" json:"rds_server_address,omitempty"`
	// Resource path specifies the resources to return. Resources paths have the
	// following format:
	// <resource_provider>://<resource_type>/<additional_params>
	//
	// Examples:
	// For GCE instances in projectA: "gcp://gce_instances/<projectA>"
	// Kubernetes Pods : "k8s://pods"
	ResourcePath *string `protobuf:"bytes,2,opt,name=resource_path,json=resourcePath" json:"resource_path,omitempty"`
	// Filters to filter resources by.
	Filter []*proto1.Filter `protobuf:"bytes,3,rep,name=filter" json:"filter,omitempty"`
	// IP config to specify the IP address to pick for a resource.
	IpConfig             *proto1.IPConfig `protobuf:"bytes,4,opt,name=ip_config,json=ipConfig" json:"ip_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RDSTargets) Reset()         { *m = RDSTargets{} }
func (m *RDSTargets) String() string { return proto.CompactTextString(m) }
func (*RDSTargets) ProtoMessage()    {}
func (*RDSTargets) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a021db69203ab7b, []int{0}
}

func (m *RDSTargets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RDSTargets.Unmarshal(m, b)
}
func (m *RDSTargets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RDSTargets.Marshal(b, m, deterministic)
}
func (m *RDSTargets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RDSTargets.Merge(m, src)
}
func (m *RDSTargets) XXX_Size() int {
	return xxx_messageInfo_RDSTargets.Size(m)
}
func (m *RDSTargets) XXX_DiscardUnknown() {
	xxx_messageInfo_RDSTargets.DiscardUnknown(m)
}

var xxx_messageInfo_RDSTargets proto.InternalMessageInfo

func (m *RDSTargets) GetRdsServerAddress() string {
	if m != nil && m.RdsServerAddress != nil {
		return *m.RdsServerAddress
	}
	return ""
}

func (m *RDSTargets) GetResourcePath() string {
	if m != nil && m.ResourcePath != nil {
		return *m.ResourcePath
	}
	return ""
}

func (m *RDSTargets) GetFilter() []*proto1.Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *RDSTargets) GetIpConfig() *proto1.IPConfig {
	if m != nil {
		return m.IpConfig
	}
	return nil
}

type TargetsDef struct {
	// Types that are valid to be assigned to Type:
	//	*TargetsDef_HostNames
	//	*TargetsDef_SharedTargets
	//	*TargetsDef_GceTargets
	//	*TargetsDef_RdsTargets
	//	*TargetsDef_RtcTargets
	//	*TargetsDef_DummyTargets
	Type isTargetsDef_Type `protobuf_oneof:"type"`
	// Regex to apply on the targets.
	Regex *string `protobuf:"bytes,21,opt,name=regex" json:"regex,omitempty"`
	// Exclude lameducks. Lameduck targets can be set through RTC (realtime
	// configurator) service. This functionality works only if lame_duck_options
	// are specified.
	ExcludeLameducks             *bool    `protobuf:"varint,22,opt,name=exclude_lameducks,json=excludeLameducks,def=1" json:"exclude_lameducks,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *TargetsDef) Reset()         { *m = TargetsDef{} }
func (m *TargetsDef) String() string { return proto.CompactTextString(m) }
func (*TargetsDef) ProtoMessage()    {}
func (*TargetsDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a021db69203ab7b, []int{1}
}

var extRange_TargetsDef = []proto.ExtensionRange{
	{Start: 200, End: 536870911},
}

func (*TargetsDef) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_TargetsDef
}

func (m *TargetsDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetsDef.Unmarshal(m, b)
}
func (m *TargetsDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetsDef.Marshal(b, m, deterministic)
}
func (m *TargetsDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetsDef.Merge(m, src)
}
func (m *TargetsDef) XXX_Size() int {
	return xxx_messageInfo_TargetsDef.Size(m)
}
func (m *TargetsDef) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetsDef.DiscardUnknown(m)
}

var xxx_messageInfo_TargetsDef proto.InternalMessageInfo

const Default_TargetsDef_ExcludeLameducks bool = true

type isTargetsDef_Type interface {
	isTargetsDef_Type()
}

type TargetsDef_HostNames struct {
	HostNames string `protobuf:"bytes,1,opt,name=host_names,json=hostNames,oneof"`
}

type TargetsDef_SharedTargets struct {
	SharedTargets string `protobuf:"bytes,5,opt,name=shared_targets,json=sharedTargets,oneof"`
}

type TargetsDef_GceTargets struct {
	GceTargets *proto2.TargetsConf `protobuf:"bytes,2,opt,name=gce_targets,json=gceTargets,oneof"`
}

type TargetsDef_RdsTargets struct {
	RdsTargets *RDSTargets `protobuf:"bytes,3,opt,name=rds_targets,json=rdsTargets,oneof"`
}

type TargetsDef_RtcTargets struct {
	RtcTargets *proto3.TargetsConf `protobuf:"bytes,4,opt,name=rtc_targets,json=rtcTargets,oneof"`
}

type TargetsDef_DummyTargets struct {
	DummyTargets *DummyTargets `protobuf:"bytes,20,opt,name=dummy_targets,json=dummyTargets,oneof"`
}

func (*TargetsDef_HostNames) isTargetsDef_Type() {}

func (*TargetsDef_SharedTargets) isTargetsDef_Type() {}

func (*TargetsDef_GceTargets) isTargetsDef_Type() {}

func (*TargetsDef_RdsTargets) isTargetsDef_Type() {}

func (*TargetsDef_RtcTargets) isTargetsDef_Type() {}

func (*TargetsDef_DummyTargets) isTargetsDef_Type() {}

func (m *TargetsDef) GetType() isTargetsDef_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *TargetsDef) GetHostNames() string {
	if x, ok := m.GetType().(*TargetsDef_HostNames); ok {
		return x.HostNames
	}
	return ""
}

func (m *TargetsDef) GetSharedTargets() string {
	if x, ok := m.GetType().(*TargetsDef_SharedTargets); ok {
		return x.SharedTargets
	}
	return ""
}

func (m *TargetsDef) GetGceTargets() *proto2.TargetsConf {
	if x, ok := m.GetType().(*TargetsDef_GceTargets); ok {
		return x.GceTargets
	}
	return nil
}

func (m *TargetsDef) GetRdsTargets() *RDSTargets {
	if x, ok := m.GetType().(*TargetsDef_RdsTargets); ok {
		return x.RdsTargets
	}
	return nil
}

func (m *TargetsDef) GetRtcTargets() *proto3.TargetsConf {
	if x, ok := m.GetType().(*TargetsDef_RtcTargets); ok {
		return x.RtcTargets
	}
	return nil
}

func (m *TargetsDef) GetDummyTargets() *DummyTargets {
	if x, ok := m.GetType().(*TargetsDef_DummyTargets); ok {
		return x.DummyTargets
	}
	return nil
}

func (m *TargetsDef) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

func (m *TargetsDef) GetExcludeLameducks() bool {
	if m != nil && m.ExcludeLameducks != nil {
		return *m.ExcludeLameducks
	}
	return Default_TargetsDef_ExcludeLameducks
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TargetsDef) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TargetsDef_HostNames)(nil),
		(*TargetsDef_SharedTargets)(nil),
		(*TargetsDef_GceTargets)(nil),
		(*TargetsDef_RdsTargets)(nil),
		(*TargetsDef_RtcTargets)(nil),
		(*TargetsDef_DummyTargets)(nil),
	}
}

// DummyTargets represent empty targets, which are useful for external
// probes that do not have any "proper" targets.  Such as ilbprober.
type DummyTargets struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyTargets) Reset()         { *m = DummyTargets{} }
func (m *DummyTargets) String() string { return proto.CompactTextString(m) }
func (*DummyTargets) ProtoMessage()    {}
func (*DummyTargets) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a021db69203ab7b, []int{2}
}

func (m *DummyTargets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyTargets.Unmarshal(m, b)
}
func (m *DummyTargets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyTargets.Marshal(b, m, deterministic)
}
func (m *DummyTargets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyTargets.Merge(m, src)
}
func (m *DummyTargets) XXX_Size() int {
	return xxx_messageInfo_DummyTargets.Size(m)
}
func (m *DummyTargets) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyTargets.DiscardUnknown(m)
}

var xxx_messageInfo_DummyTargets proto.InternalMessageInfo

// Global targets options. These options are independent of the per-probe
// targets which are defined by the "Targets" type above.
//
// Currently these options are used only for GCE targets to control things like
// how often to re-evaluate the targets and whether to check for lame ducks or
// not.
type GlobalTargetsOptions struct {
	// RDS server address
	RdsServerAddress *string `protobuf:"bytes,3,opt,name=rds_server_address,json=rdsServerAddress" json:"rds_server_address,omitempty"`
	// GCE targets options.
	GlobalGceTargetsOptions *proto2.GlobalOptions `protobuf:"bytes,1,opt,name=global_gce_targets_options,json=globalGceTargetsOptions" json:"global_gce_targets_options,omitempty"`
	// Lame duck options. If provided, targets module checks for the lame duck
	// targets and removes them from the targets list.
	LameDuckOptions      *proto4.Options `protobuf:"bytes,2,opt,name=lame_duck_options,json=lameDuckOptions" json:"lame_duck_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GlobalTargetsOptions) Reset()         { *m = GlobalTargetsOptions{} }
func (m *GlobalTargetsOptions) String() string { return proto.CompactTextString(m) }
func (*GlobalTargetsOptions) ProtoMessage()    {}
func (*GlobalTargetsOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a021db69203ab7b, []int{3}
}

func (m *GlobalTargetsOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalTargetsOptions.Unmarshal(m, b)
}
func (m *GlobalTargetsOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalTargetsOptions.Marshal(b, m, deterministic)
}
func (m *GlobalTargetsOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalTargetsOptions.Merge(m, src)
}
func (m *GlobalTargetsOptions) XXX_Size() int {
	return xxx_messageInfo_GlobalTargetsOptions.Size(m)
}
func (m *GlobalTargetsOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalTargetsOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalTargetsOptions proto.InternalMessageInfo

func (m *GlobalTargetsOptions) GetRdsServerAddress() string {
	if m != nil && m.RdsServerAddress != nil {
		return *m.RdsServerAddress
	}
	return ""
}

func (m *GlobalTargetsOptions) GetGlobalGceTargetsOptions() *proto2.GlobalOptions {
	if m != nil {
		return m.GlobalGceTargetsOptions
	}
	return nil
}

func (m *GlobalTargetsOptions) GetLameDuckOptions() *proto4.Options {
	if m != nil {
		return m.LameDuckOptions
	}
	return nil
}

func init() {
	proto.RegisterType((*RDSTargets)(nil), "cloudprober.targets.RDSTargets")
	proto.RegisterType((*TargetsDef)(nil), "cloudprober.targets.TargetsDef")
	proto.RegisterType((*DummyTargets)(nil), "cloudprober.targets.DummyTargets")
	proto.RegisterType((*GlobalTargetsOptions)(nil), "cloudprober.targets.GlobalTargetsOptions")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/targets/proto/targets.proto", fileDescriptor_6a021db69203ab7b)
}

var fileDescriptor_6a021db69203ab7b = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x6f, 0xda, 0x4c,
	0x10, 0xc7, 0xe3, 0x40, 0x22, 0x18, 0x20, 0x0f, 0xf1, 0x43, 0x1b, 0x97, 0x4b, 0x28, 0x7d, 0x43,
	0x55, 0x65, 0x14, 0x0e, 0x95, 0x5a, 0xf5, 0x92, 0x14, 0x15, 0x2a, 0x55, 0x6d, 0xea, 0xf4, 0x6e,
	0x99, 0xdd, 0xc1, 0x58, 0x31, 0xac, 0x35, 0x5e, 0x57, 0xc9, 0x8d, 0x8f, 0x97, 0x73, 0x3f, 0x4f,
	0x0f, 0x95, 0xed, 0x5d, 0x62, 0xb5, 0x26, 0xe2, 0xe6, 0x9d, 0xf9, 0xcf, 0xcf, 0xff, 0x79, 0x81,
	0x77, 0x7e, 0x20, 0x17, 0xc9, 0xcc, 0x66, 0x62, 0x39, 0xf4, 0x85, 0xf0, 0x43, 0x1c, 0xb2, 0x50,
	0x24, 0x3c, 0x22, 0x31, 0x43, 0x1a, 0x4a, 0x8f, 0x7c, 0x94, 0xf1, 0x30, 0x22, 0x21, 0x85, 0x7e,
	0xd9, 0xd9, 0xcb, 0xfc, 0xbf, 0x20, 0xb4, 0x55, 0xaa, 0x7b, 0xf6, 0x30, 0x8f, 0xb8, 0x66, 0x11,
	0x57, 0x9c, 0xee, 0x87, 0xdd, 0x2c, 0xf8, 0x0c, 0x55, 0x29, 0x13, 0xab, 0x79, 0xe0, 0xab, 0xea,
	0xf3, 0xdd, 0xaa, 0x43, 0x6f, 0x89, 0x3c, 0x61, 0xd7, 0x65, 0x88, 0x1d, 0x0d, 0x90, 0x64, 0x25,
	0xd5, 0xfd, 0x3b, 0x03, 0xc0, 0x19, 0x5f, 0xfd, 0xc8, 0x55, 0xe6, 0x1b, 0x30, 0x89, 0xc7, 0x6e,
	0x8c, 0xf4, 0x13, 0xc9, 0xf5, 0x38, 0x27, 0x8c, 0x63, 0xcb, 0xe8, 0x19, 0x83, 0xba, 0xd3, 0x26,
	0x1e, 0x5f, 0x65, 0x89, 0xf3, 0x3c, 0x6e, 0x3e, 0x83, 0x16, 0x61, 0x2c, 0x12, 0x62, 0xe8, 0x46,
	0x9e, 0x5c, 0x58, 0xfb, 0x99, 0xb0, 0xa9, 0x83, 0x97, 0x9e, 0x5c, 0x98, 0x43, 0x38, 0x9c, 0x07,
	0xa1, 0x44, 0xb2, 0x2a, 0xbd, 0xca, 0xa0, 0x31, 0x3a, 0xb1, 0x8b, 0x93, 0x4f, 0x07, 0xf9, 0x29,
	0x4b, 0x3b, 0x4a, 0x66, 0xbe, 0x85, 0x7a, 0x10, 0xb9, 0xb9, 0x4b, 0xab, 0xda, 0x33, 0x06, 0x8d,
	0xd1, 0x93, 0x7f, 0x6a, 0x3e, 0x5f, 0x7e, 0xcc, 0x04, 0x4e, 0x2d, 0x88, 0xf2, 0xaf, 0xfe, 0xaf,
	0x0a, 0x80, 0xea, 0x63, 0x8c, 0x73, 0xf3, 0x14, 0x60, 0x21, 0x62, 0xe9, 0xae, 0xbc, 0x25, 0xaa,
	0x16, 0xa6, 0x7b, 0x4e, 0x3d, 0x8d, 0x7d, 0x4d, 0x43, 0xe6, 0x2b, 0x38, 0x8a, 0x17, 0x1e, 0x21,
	0x77, 0xd5, 0x8c, 0xac, 0x03, 0x25, 0x6a, 0xe5, 0x71, 0x3d, 0x94, 0x09, 0x34, 0x7c, 0x86, 0x1b,
	0xd5, 0x7e, 0x66, 0xe9, 0xb9, 0x5d, 0x72, 0x40, 0xb6, 0xcf, 0xd0, 0x56, 0x65, 0xa9, 0xab, 0xe9,
	0x9e, 0x03, 0x3e, 0x43, 0x0d, 0xba, 0x80, 0x46, 0x3a, 0x5d, 0x0d, 0xaa, 0x64, 0xa0, 0xd3, 0x52,
	0xd0, 0xfd, 0x4e, 0x52, 0x06, 0xf1, 0xb8, 0x60, 0x86, 0x24, 0xdb, 0x30, 0xaa, 0x0f, 0x98, 0x21,
	0xc9, 0xfe, 0x36, 0x43, 0x92, 0x69, 0xd0, 0x14, 0x5a, 0x3c, 0x59, 0x2e, 0x6f, 0x37, 0xa8, 0x4e,
	0x86, 0x7a, 0x5a, 0x8a, 0x1a, 0xa7, 0xca, 0x7b, 0x43, 0x4d, 0x5e, 0x78, 0x9b, 0x1d, 0x38, 0x20,
	0xf4, 0xf1, 0xc6, 0x7a, 0x94, 0xad, 0x3f, 0x7f, 0x98, 0x67, 0x70, 0x8c, 0x37, 0x2c, 0x4c, 0x38,
	0xba, 0xfa, 0x7c, 0x63, 0xeb, 0x71, 0xcf, 0x18, 0xd4, 0xde, 0x57, 0x25, 0x25, 0xe8, 0xb4, 0x55,
	0xfa, 0x8b, 0xce, 0xbe, 0xae, 0xd7, 0xee, 0x8c, 0xf6, 0x7a, 0xbd, 0x5e, 0xef, 0x5f, 0x1c, 0x42,
	0x55, 0xde, 0x46, 0xd8, 0x3f, 0x82, 0x66, 0xf1, 0xdf, 0xfd, 0xdf, 0x06, 0x74, 0x26, 0xa1, 0x98,
	0x79, 0xa1, 0x8a, 0x7c, 0x8b, 0x64, 0x20, 0x56, 0xdb, 0x2e, 0xb7, 0xb2, 0xe5, 0x72, 0x19, 0x74,
	0xfd, 0x8c, 0xe2, 0x16, 0x36, 0xeb, 0x8a, 0x9c, 0x95, 0x1d, 0x4b, 0x63, 0xf4, 0x72, 0xeb, 0x86,
	0x73, 0x03, 0xea, 0xcf, 0xce, 0x49, 0x4e, 0x9a, 0x6c, 0xf6, 0xac, 0x2d, 0x7d, 0x87, 0xe3, 0xb4,
	0x73, 0x37, 0x6d, 0x6e, 0xc3, 0xce, 0xaf, 0xe7, 0x45, 0x29, 0x5b, 0xcf, 0xc9, 0xd6, 0xe8, 0xff,
	0xd2, 0xc8, 0x38, 0x61, 0xd7, 0x2a, 0xf0, 0x27, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xad, 0x8a, 0x8c,
	0xf1, 0x04, 0x00, 0x00,
}
