// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/servers/http/config.proto

/*
Package http is a generated protocol buffer package.

It is generated from these files:
	github.com/google/cloudprober/servers/http/config.proto

It has these top-level messages:
	ServerConf
*/
package http

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerConf struct {
	Port *int32 `protobuf:"varint,1,opt,name=port,def=3141" json:"port,omitempty"`
	// Maximum duration for reading the entire request, including the body.
	ReadTimeoutMs *int32 `protobuf:"varint,2,opt,name=read_timeout_ms,json=readTimeoutMs,def=10000" json:"read_timeout_ms,omitempty"`
	// Maximum duration before timing out writes of the response.
	WriteTimeoutMs *int32 `protobuf:"varint,3,opt,name=write_timeout_ms,json=writeTimeoutMs,def=10000" json:"write_timeout_ms,omitempty"`
	// Maximum amount of time to wait for the next request when keep-alives are
	// enabled.
	IdleTimeoutMs *int32 `protobuf:"varint,4,opt,name=idle_timeout_ms,json=idleTimeoutMs,def=60000" json:"idle_timeout_ms,omitempty"`
	// Pattern data handler returns pattern data at the url /data_<size_in_bytes>,
	// e.g. "/data_2048".
	PatternDataHandler []*ServerConf_PatternDataHandler `protobuf:"bytes,5,rep,name=pattern_data_handler,json=patternDataHandler" json:"pattern_data_handler,omitempty"`
	XXX_unrecognized   []byte                           `json:"-"`
}

func (m *ServerConf) Reset()                    { *m = ServerConf{} }
func (m *ServerConf) String() string            { return proto.CompactTextString(m) }
func (*ServerConf) ProtoMessage()               {}
func (*ServerConf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_ServerConf_Port int32 = 3141
const Default_ServerConf_ReadTimeoutMs int32 = 10000
const Default_ServerConf_WriteTimeoutMs int32 = 10000
const Default_ServerConf_IdleTimeoutMs int32 = 60000

func (m *ServerConf) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return Default_ServerConf_Port
}

func (m *ServerConf) GetReadTimeoutMs() int32 {
	if m != nil && m.ReadTimeoutMs != nil {
		return *m.ReadTimeoutMs
	}
	return Default_ServerConf_ReadTimeoutMs
}

func (m *ServerConf) GetWriteTimeoutMs() int32 {
	if m != nil && m.WriteTimeoutMs != nil {
		return *m.WriteTimeoutMs
	}
	return Default_ServerConf_WriteTimeoutMs
}

func (m *ServerConf) GetIdleTimeoutMs() int32 {
	if m != nil && m.IdleTimeoutMs != nil {
		return *m.IdleTimeoutMs
	}
	return Default_ServerConf_IdleTimeoutMs
}

func (m *ServerConf) GetPatternDataHandler() []*ServerConf_PatternDataHandler {
	if m != nil {
		return m.PatternDataHandler
	}
	return nil
}

type ServerConf_PatternDataHandler struct {
	// Response sizes to server, e.g. 1024.
	ResponseSize *int32 `protobuf:"varint,1,req,name=response_size,json=responseSize" json:"response_size,omitempty"`
	// Pattern is repeated to build the response, with "response_size mod
	// pattern_size" filled by '0' bytes.
	Pattern          *string `protobuf:"bytes,2,opt,name=pattern,def=cloudprober" json:"pattern,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerConf_PatternDataHandler) Reset()         { *m = ServerConf_PatternDataHandler{} }
func (m *ServerConf_PatternDataHandler) String() string { return proto.CompactTextString(m) }
func (*ServerConf_PatternDataHandler) ProtoMessage()    {}
func (*ServerConf_PatternDataHandler) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

const Default_ServerConf_PatternDataHandler_Pattern string = "cloudprober"

func (m *ServerConf_PatternDataHandler) GetResponseSize() int32 {
	if m != nil && m.ResponseSize != nil {
		return *m.ResponseSize
	}
	return 0
}

func (m *ServerConf_PatternDataHandler) GetPattern() string {
	if m != nil && m.Pattern != nil {
		return *m.Pattern
	}
	return Default_ServerConf_PatternDataHandler_Pattern
}

func init() {
	proto.RegisterType((*ServerConf)(nil), "cloudprober.servers.http.ServerConf")
	proto.RegisterType((*ServerConf_PatternDataHandler)(nil), "cloudprober.servers.http.ServerConf.PatternDataHandler")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/servers/http/config.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd0, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0x06, 0x70, 0xfa, 0x27, 0xbc, 0xbc, 0x5b, 0x6b, 0x65, 0xf1, 0xb0, 0x78, 0x2a, 0x8a, 0xd0,
	0x4b, 0x77, 0x53, 0x15, 0x0b, 0xbd, 0xea, 0xc1, 0x8b, 0x20, 0xa9, 0xf7, 0xb8, 0x6d, 0xa6, 0xe9,
	0x42, 0x9a, 0x59, 0x76, 0x27, 0x0a, 0x3d, 0xfa, 0xc9, 0x25, 0x49, 0x4b, 0x22, 0xc5, 0xeb, 0xf3,
	0xfc, 0x66, 0xd8, 0x59, 0x36, 0x4f, 0x0d, 0x6d, 0x8b, 0x95, 0x5c, 0xe3, 0x4e, 0xa5, 0x88, 0x69,
	0x06, 0x6a, 0x9d, 0x61, 0x91, 0x58, 0x87, 0x2b, 0x70, 0xca, 0x83, 0xfb, 0x04, 0xe7, 0xd5, 0x96,
	0xc8, 0xaa, 0x35, 0xe6, 0x1b, 0x93, 0x4a, 0xeb, 0x90, 0x90, 0x8b, 0x16, 0x93, 0x07, 0x26, 0x4b,
	0x76, 0xfd, 0xdd, 0x63, 0x6c, 0x59, 0x05, 0x4f, 0x98, 0x6f, 0xb8, 0x60, 0x7d, 0x8b, 0x8e, 0x44,
	0x67, 0xdc, 0x99, 0x04, 0x8b, 0xfe, 0xfd, 0xec, 0x61, 0x16, 0x55, 0x09, 0x9f, 0xb2, 0x91, 0x03,
	0x9d, 0xc4, 0x64, 0x76, 0x80, 0x05, 0xc5, 0x3b, 0x2f, 0xba, 0x15, 0x0a, 0x66, 0x61, 0x18, 0x86,
	0xd1, 0xb0, 0x6c, 0xdf, 0xeb, 0xf2, 0xd5, 0x73, 0xc5, 0x2e, 0xbe, 0x9c, 0x21, 0x68, 0xfb, 0x5e,
	0xdb, 0x9f, 0x57, 0x75, 0x33, 0x30, 0x65, 0x23, 0x93, 0x64, 0xbf, 0x7c, 0xbf, 0xf6, 0x8f, 0xf5,
	0xfe, 0xb2, 0x6d, 0xb8, 0x61, 0x97, 0x56, 0x13, 0x81, 0xcb, 0xe3, 0x44, 0x93, 0x8e, 0xb7, 0x3a,
	0x4f, 0x32, 0x70, 0x22, 0x18, 0xf7, 0x26, 0x83, 0xbb, 0xb9, 0xfc, 0xeb, 0x60, 0xd9, 0x1c, 0x2b,
	0xdf, 0xea, 0x05, 0xcf, 0x9a, 0xf4, 0x4b, 0x3d, 0x1e, 0x71, 0x7b, 0x92, 0x5d, 0x7d, 0x30, 0x7e,
	0x2a, 0xf9, 0x0d, 0x1b, 0x3a, 0xf0, 0x16, 0x73, 0x0f, 0xb1, 0x37, 0x7b, 0x10, 0x9d, 0x71, 0x77,
	0x12, 0x44, 0x67, 0xc7, 0x70, 0x69, 0xf6, 0xc0, 0x6f, 0xd9, 0xbf, 0xc3, 0xc2, 0xea, 0xb3, 0xfe,
	0x2f, 0x06, 0xad, 0x77, 0x45, 0xc7, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0x61, 0x67, 0x2a, 0x3c,
	0xd8, 0x01, 0x00, 0x00,
}
