// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/common/tlsconfig/proto/config.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TLSConfig struct {
	// CA certificate file to verify certificates provided by the other party.
	CaCertFile *string `protobuf:"bytes,1,opt,name=ca_cert_file,json=caCertFile" json:"ca_cert_file,omitempty"`
	// Local certificate file.
	TlsCertFile *string `protobuf:"bytes,2,opt,name=tls_cert_file,json=tlsCertFile" json:"tls_cert_file,omitempty"`
	// Private key file corresponding to the certificate above.
	TlsKeyFile *string `protobuf:"bytes,3,opt,name=tls_key_file,json=tlsKeyFile" json:"tls_key_file,omitempty"`
	// Whether to ignore the cert validation.
	DisableCertValidation *bool    `protobuf:"varint,4,opt,name=disable_cert_validation,json=disableCertValidation" json:"disable_cert_validation,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *TLSConfig) Reset()         { *m = TLSConfig{} }
func (m *TLSConfig) String() string { return proto.CompactTextString(m) }
func (*TLSConfig) ProtoMessage()    {}
func (*TLSConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7991ca145ec7ed9, []int{0}
}

func (m *TLSConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLSConfig.Unmarshal(m, b)
}
func (m *TLSConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLSConfig.Marshal(b, m, deterministic)
}
func (m *TLSConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLSConfig.Merge(m, src)
}
func (m *TLSConfig) XXX_Size() int {
	return xxx_messageInfo_TLSConfig.Size(m)
}
func (m *TLSConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TLSConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TLSConfig proto.InternalMessageInfo

func (m *TLSConfig) GetCaCertFile() string {
	if m != nil && m.CaCertFile != nil {
		return *m.CaCertFile
	}
	return ""
}

func (m *TLSConfig) GetTlsCertFile() string {
	if m != nil && m.TlsCertFile != nil {
		return *m.TlsCertFile
	}
	return ""
}

func (m *TLSConfig) GetTlsKeyFile() string {
	if m != nil && m.TlsKeyFile != nil {
		return *m.TlsKeyFile
	}
	return ""
}

func (m *TLSConfig) GetDisableCertValidation() bool {
	if m != nil && m.DisableCertValidation != nil {
		return *m.DisableCertValidation
	}
	return false
}

func init() {
	proto.RegisterType((*TLSConfig)(nil), "cloudprober.tlsconfig.TLSConfig")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/common/tlsconfig/proto/config.proto", fileDescriptor_c7991ca145ec7ed9)
}

var fileDescriptor_c7991ca145ec7ed9 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcc, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x71, 0x19, 0x18, 0xa8, 0x29, 0x4b, 0xa4, 0x8a, 0x8e, 0x56, 0xa7, 0x4e, 0xf1, 0xc6,
	0x8e, 0x2a, 0xb1, 0xc0, 0x14, 0x10, 0x6b, 0xe4, 0x38, 0x17, 0x63, 0x71, 0xc9, 0x45, 0xf6, 0x05,
	0x29, 0xcf, 0xc4, 0x4b, 0xa2, 0xd8, 0x55, 0x94, 0xf1, 0xd3, 0xfd, 0xee, 0x2f, 0x5f, 0x9c, 0xe7,
	0xef, 0xa9, 0x29, 0x2d, 0xf5, 0xda, 0x11, 0x39, 0x04, 0x6d, 0x91, 0xa6, 0x76, 0x0c, 0xd4, 0x40,
	0xd0, 0x96, 0xfa, 0x9e, 0x06, 0xcd, 0x18, 0x2d, 0x0d, 0x9d, 0x77, 0x7a, 0x0c, 0xc4, 0xa4, 0xf3,
	0x28, 0xd3, 0x28, 0x0e, 0x9b, 0x87, 0x72, 0x95, 0xa7, 0x3f, 0x21, 0x77, 0x9f, 0xef, 0x1f, 0x97,
	0xb4, 0x0a, 0x25, 0xf7, 0xd6, 0xd4, 0x16, 0x02, 0xd7, 0x9d, 0x47, 0x38, 0x0a, 0x25, 0xce, 0xbb,
	0x4a, 0x5a, 0x73, 0x81, 0xc0, 0xaf, 0x1e, 0xa1, 0x38, 0xc9, 0x47, 0xc6, 0xb8, 0x21, 0x37, 0x89,
	0x3c, 0x30, 0xc6, 0xd5, 0x28, 0xb9, 0x5f, 0xcc, 0x0f, 0xcc, 0x99, 0xdc, 0xe6, 0x0a, 0x63, 0x7c,
	0x83, 0x39, 0x89, 0x67, 0xf9, 0xd4, 0xfa, 0x68, 0x1a, 0x84, 0x5c, 0xfa, 0x35, 0xe8, 0x5b, 0xc3,
	0x9e, 0x86, 0xe3, 0x9d, 0x12, 0xe7, 0xfb, 0xea, 0x70, 0x3d, 0x2f, 0xcd, 0xaf, 0xf5, 0xf8, 0x1f,
	0x00, 0x00, 0xff, 0xff, 0x42, 0x9c, 0xb5, 0xaa, 0x08, 0x01, 0x00, 0x00,
}
