// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/rds/gcp/proto/config.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GCEInstances struct {
	// Optional zone filter regex to limit discovery to the specific zones
	// For example, zone_filter: "us-east1-*" will limit instances discovery to
	// only to the zones in the "us-east1" region.
	ZoneFilter *string `protobuf:"bytes,1,opt,name=zone_filter,json=zoneFilter" json:"zone_filter,omitempty"`
	// How often resources should be refreshed.
	ReEvalSec            *int32   `protobuf:"varint,98,opt,name=re_eval_sec,json=reEvalSec,def=300" json:"re_eval_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCEInstances) Reset()         { *m = GCEInstances{} }
func (m *GCEInstances) String() string { return proto.CompactTextString(m) }
func (*GCEInstances) ProtoMessage()    {}
func (*GCEInstances) Descriptor() ([]byte, []int) {
	return fileDescriptor_182df064313f089d, []int{0}
}

func (m *GCEInstances) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCEInstances.Unmarshal(m, b)
}
func (m *GCEInstances) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCEInstances.Marshal(b, m, deterministic)
}
func (m *GCEInstances) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCEInstances.Merge(m, src)
}
func (m *GCEInstances) XXX_Size() int {
	return xxx_messageInfo_GCEInstances.Size(m)
}
func (m *GCEInstances) XXX_DiscardUnknown() {
	xxx_messageInfo_GCEInstances.DiscardUnknown(m)
}

var xxx_messageInfo_GCEInstances proto.InternalMessageInfo

const Default_GCEInstances_ReEvalSec int32 = 300

func (m *GCEInstances) GetZoneFilter() string {
	if m != nil && m.ZoneFilter != nil {
		return *m.ZoneFilter
	}
	return ""
}

func (m *GCEInstances) GetReEvalSec() int32 {
	if m != nil && m.ReEvalSec != nil {
		return *m.ReEvalSec
	}
	return Default_GCEInstances_ReEvalSec
}

type ForwardingRules struct {
	// Optionl region filter regex to limit discovery to specific regions, e.g.
	// "region_filter:europe-*"
	RegionFilter *string `protobuf:"bytes,1,opt,name=region_filter,json=regionFilter" json:"region_filter,omitempty"`
	// How often resources should be refreshed.
	ReEvalSec            *int32   `protobuf:"varint,98,opt,name=re_eval_sec,json=reEvalSec,def=300" json:"re_eval_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardingRules) Reset()         { *m = ForwardingRules{} }
func (m *ForwardingRules) String() string { return proto.CompactTextString(m) }
func (*ForwardingRules) ProtoMessage()    {}
func (*ForwardingRules) Descriptor() ([]byte, []int) {
	return fileDescriptor_182df064313f089d, []int{1}
}

func (m *ForwardingRules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardingRules.Unmarshal(m, b)
}
func (m *ForwardingRules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardingRules.Marshal(b, m, deterministic)
}
func (m *ForwardingRules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardingRules.Merge(m, src)
}
func (m *ForwardingRules) XXX_Size() int {
	return xxx_messageInfo_ForwardingRules.Size(m)
}
func (m *ForwardingRules) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardingRules.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardingRules proto.InternalMessageInfo

const Default_ForwardingRules_ReEvalSec int32 = 300

func (m *ForwardingRules) GetRegionFilter() string {
	if m != nil && m.RegionFilter != nil {
		return *m.RegionFilter
	}
	return ""
}

func (m *ForwardingRules) GetReEvalSec() int32 {
	if m != nil && m.ReEvalSec != nil {
		return *m.ReEvalSec
	}
	return Default_ForwardingRules_ReEvalSec
}

// Runtime configurator variables.
type RTCVariables struct {
	RtcConfig            []*RTCVariables_RTCConfig `protobuf:"bytes,1,rep,name=rtc_config,json=rtcConfig" json:"rtc_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RTCVariables) Reset()         { *m = RTCVariables{} }
func (m *RTCVariables) String() string { return proto.CompactTextString(m) }
func (*RTCVariables) ProtoMessage()    {}
func (*RTCVariables) Descriptor() ([]byte, []int) {
	return fileDescriptor_182df064313f089d, []int{2}
}

func (m *RTCVariables) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RTCVariables.Unmarshal(m, b)
}
func (m *RTCVariables) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RTCVariables.Marshal(b, m, deterministic)
}
func (m *RTCVariables) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RTCVariables.Merge(m, src)
}
func (m *RTCVariables) XXX_Size() int {
	return xxx_messageInfo_RTCVariables.Size(m)
}
func (m *RTCVariables) XXX_DiscardUnknown() {
	xxx_messageInfo_RTCVariables.DiscardUnknown(m)
}

var xxx_messageInfo_RTCVariables proto.InternalMessageInfo

func (m *RTCVariables) GetRtcConfig() []*RTCVariables_RTCConfig {
	if m != nil {
		return m.RtcConfig
	}
	return nil
}

type RTCVariables_RTCConfig struct {
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// How often RTC variables should be evaluated/expanded.
	ReEvalSec            *int32   `protobuf:"varint,2,opt,name=re_eval_sec,json=reEvalSec,def=10" json:"re_eval_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RTCVariables_RTCConfig) Reset()         { *m = RTCVariables_RTCConfig{} }
func (m *RTCVariables_RTCConfig) String() string { return proto.CompactTextString(m) }
func (*RTCVariables_RTCConfig) ProtoMessage()    {}
func (*RTCVariables_RTCConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_182df064313f089d, []int{2, 0}
}

func (m *RTCVariables_RTCConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RTCVariables_RTCConfig.Unmarshal(m, b)
}
func (m *RTCVariables_RTCConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RTCVariables_RTCConfig.Marshal(b, m, deterministic)
}
func (m *RTCVariables_RTCConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RTCVariables_RTCConfig.Merge(m, src)
}
func (m *RTCVariables_RTCConfig) XXX_Size() int {
	return xxx_messageInfo_RTCVariables_RTCConfig.Size(m)
}
func (m *RTCVariables_RTCConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RTCVariables_RTCConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RTCVariables_RTCConfig proto.InternalMessageInfo

const Default_RTCVariables_RTCConfig_ReEvalSec int32 = 10

func (m *RTCVariables_RTCConfig) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RTCVariables_RTCConfig) GetReEvalSec() int32 {
	if m != nil && m.ReEvalSec != nil {
		return *m.ReEvalSec
	}
	return Default_RTCVariables_RTCConfig_ReEvalSec
}

// Runtime configurator variables.
type PubSubMessages struct {
	Subscription []*PubSubMessages_Subscription `protobuf:"bytes,1,rep,name=subscription" json:"subscription,omitempty"`
	// Only for testing.
	ApiEndpoint          *string  `protobuf:"bytes,2,opt,name=api_endpoint,json=apiEndpoint" json:"api_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubSubMessages) Reset()         { *m = PubSubMessages{} }
func (m *PubSubMessages) String() string { return proto.CompactTextString(m) }
func (*PubSubMessages) ProtoMessage()    {}
func (*PubSubMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_182df064313f089d, []int{3}
}

func (m *PubSubMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubSubMessages.Unmarshal(m, b)
}
func (m *PubSubMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubSubMessages.Marshal(b, m, deterministic)
}
func (m *PubSubMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubSubMessages.Merge(m, src)
}
func (m *PubSubMessages) XXX_Size() int {
	return xxx_messageInfo_PubSubMessages.Size(m)
}
func (m *PubSubMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_PubSubMessages.DiscardUnknown(m)
}

var xxx_messageInfo_PubSubMessages proto.InternalMessageInfo

func (m *PubSubMessages) GetSubscription() []*PubSubMessages_Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

func (m *PubSubMessages) GetApiEndpoint() string {
	if m != nil && m.ApiEndpoint != nil {
		return *m.ApiEndpoint
	}
	return ""
}

type PubSubMessages_Subscription struct {
	// Subscription name. If it doesn't exist already, we try to create one.
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// Topic name. This is used to create the subscription if it doesn't exist
	// already.
	TopicName *string `protobuf:"bytes,2,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	// If subscription already exists, how far back to seek back on restart.
	// Note that duplicate data is fine as we filter by publish time.
	SeekBackDurationSec  *int32   `protobuf:"varint,3,opt,name=seek_back_duration_sec,json=seekBackDurationSec,def=3600" json:"seek_back_duration_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubSubMessages_Subscription) Reset()         { *m = PubSubMessages_Subscription{} }
func (m *PubSubMessages_Subscription) String() string { return proto.CompactTextString(m) }
func (*PubSubMessages_Subscription) ProtoMessage()    {}
func (*PubSubMessages_Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_182df064313f089d, []int{3, 0}
}

func (m *PubSubMessages_Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubSubMessages_Subscription.Unmarshal(m, b)
}
func (m *PubSubMessages_Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubSubMessages_Subscription.Marshal(b, m, deterministic)
}
func (m *PubSubMessages_Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubSubMessages_Subscription.Merge(m, src)
}
func (m *PubSubMessages_Subscription) XXX_Size() int {
	return xxx_messageInfo_PubSubMessages_Subscription.Size(m)
}
func (m *PubSubMessages_Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_PubSubMessages_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_PubSubMessages_Subscription proto.InternalMessageInfo

const Default_PubSubMessages_Subscription_SeekBackDurationSec int32 = 3600

func (m *PubSubMessages_Subscription) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PubSubMessages_Subscription) GetTopicName() string {
	if m != nil && m.TopicName != nil {
		return *m.TopicName
	}
	return ""
}

func (m *PubSubMessages_Subscription) GetSeekBackDurationSec() int32 {
	if m != nil && m.SeekBackDurationSec != nil {
		return *m.SeekBackDurationSec
	}
	return Default_PubSubMessages_Subscription_SeekBackDurationSec
}

// GCP provider config.
type ProviderConfig struct {
	// GCP projects. If running on GCE, it defaults to the local project.
	Project []string `protobuf:"bytes,1,rep,name=project" json:"project,omitempty"`
	// GCE instances discovery options. This field should be declared for the GCE
	// instances discovery to be enabled.
	GceInstances *GCEInstances `protobuf:"bytes,2,opt,name=gce_instances,json=gceInstances" json:"gce_instances,omitempty"`
	// Forwarding rules discovery options. This field should be declared for the
	// forwarding rules discovery to be enabled.
	// Note that RDS supports only regional forwarding rules.
	ForwardingRules *ForwardingRules `protobuf:"bytes,3,opt,name=forwarding_rules,json=forwardingRules" json:"forwarding_rules,omitempty"`
	// RTC variables discovery options.
	RtcVariables *RTCVariables `protobuf:"bytes,4,opt,name=rtc_variables,json=rtcVariables" json:"rtc_variables,omitempty"`
	// PubSub messages discovery options.
	PubsubMessages *PubSubMessages `protobuf:"bytes,5,opt,name=pubsub_messages,json=pubsubMessages" json:"pubsub_messages,omitempty"`
	// Compute API version.
	ApiVersion           *string  `protobuf:"bytes,99,opt,name=api_version,json=apiVersion,def=v1" json:"api_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderConfig) Reset()         { *m = ProviderConfig{} }
func (m *ProviderConfig) String() string { return proto.CompactTextString(m) }
func (*ProviderConfig) ProtoMessage()    {}
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_182df064313f089d, []int{4}
}

func (m *ProviderConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderConfig.Unmarshal(m, b)
}
func (m *ProviderConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderConfig.Marshal(b, m, deterministic)
}
func (m *ProviderConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderConfig.Merge(m, src)
}
func (m *ProviderConfig) XXX_Size() int {
	return xxx_messageInfo_ProviderConfig.Size(m)
}
func (m *ProviderConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderConfig proto.InternalMessageInfo

const Default_ProviderConfig_ApiVersion string = "v1"

func (m *ProviderConfig) GetProject() []string {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *ProviderConfig) GetGceInstances() *GCEInstances {
	if m != nil {
		return m.GceInstances
	}
	return nil
}

func (m *ProviderConfig) GetForwardingRules() *ForwardingRules {
	if m != nil {
		return m.ForwardingRules
	}
	return nil
}

func (m *ProviderConfig) GetRtcVariables() *RTCVariables {
	if m != nil {
		return m.RtcVariables
	}
	return nil
}

func (m *ProviderConfig) GetPubsubMessages() *PubSubMessages {
	if m != nil {
		return m.PubsubMessages
	}
	return nil
}

func (m *ProviderConfig) GetApiVersion() string {
	if m != nil && m.ApiVersion != nil {
		return *m.ApiVersion
	}
	return Default_ProviderConfig_ApiVersion
}

func init() {
	proto.RegisterType((*GCEInstances)(nil), "cloudprober.rds.gcp.GCEInstances")
	proto.RegisterType((*ForwardingRules)(nil), "cloudprober.rds.gcp.ForwardingRules")
	proto.RegisterType((*RTCVariables)(nil), "cloudprober.rds.gcp.RTCVariables")
	proto.RegisterType((*RTCVariables_RTCConfig)(nil), "cloudprober.rds.gcp.RTCVariables.RTCConfig")
	proto.RegisterType((*PubSubMessages)(nil), "cloudprober.rds.gcp.PubSubMessages")
	proto.RegisterType((*PubSubMessages_Subscription)(nil), "cloudprober.rds.gcp.PubSubMessages.Subscription")
	proto.RegisterType((*ProviderConfig)(nil), "cloudprober.rds.gcp.ProviderConfig")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/rds/gcp/proto/config.proto", fileDescriptor_182df064313f089d)
}

var fileDescriptor_182df064313f089d = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x5f, 0x6b, 0xdb, 0x3c,
	0x14, 0xc6, 0x71, 0xda, 0xf2, 0xe2, 0x63, 0xb7, 0x79, 0x71, 0x61, 0x98, 0xc2, 0x58, 0x9a, 0xec,
	0x22, 0x30, 0xb0, 0xd3, 0x14, 0xc6, 0xd6, 0xcb, 0x65, 0xc9, 0xd8, 0xd8, 0x3f, 0x94, 0xd0, 0x9b,
	0x5d, 0x08, 0x59, 0x56, 0x3c, 0x2d, 0x8e, 0x25, 0x24, 0xdb, 0x83, 0xb1, 0xfb, 0x7d, 0x8c, 0x7d,
	0xd3, 0x31, 0x24, 0x27, 0xa9, 0x53, 0xc2, 0xd8, 0xee, 0xa4, 0x47, 0x3a, 0x0f, 0xcf, 0x39, 0xe7,
	0x07, 0xcf, 0x32, 0x5e, 0x7e, 0xae, 0x92, 0x88, 0x8a, 0x75, 0x9c, 0x09, 0x91, 0xe5, 0x2c, 0xa6,
	0xb9, 0xa8, 0x52, 0xa9, 0x44, 0xc2, 0x54, 0xac, 0x52, 0x1d, 0x67, 0x54, 0xc6, 0x52, 0x89, 0x52,
	0xc4, 0x54, 0x14, 0x4b, 0x9e, 0x45, 0xf6, 0x12, 0x9c, 0xb7, 0xfe, 0x45, 0x2a, 0xd5, 0x51, 0x46,
	0x65, 0x7f, 0x01, 0xfe, 0xab, 0xc9, 0xf4, 0x75, 0xa1, 0x4b, 0x52, 0x50, 0xa6, 0x83, 0x47, 0xe0,
	0x7d, 0x13, 0x05, 0xc3, 0x4b, 0x9e, 0x97, 0x4c, 0x85, 0x4e, 0xcf, 0x19, 0xba, 0x08, 0x8c, 0x34,
	0xb3, 0x4a, 0x30, 0x00, 0x4f, 0x31, 0xcc, 0x6a, 0x92, 0x63, 0xcd, 0x68, 0x98, 0xf4, 0x9c, 0xe1,
	0xc9, 0xcd, 0xd1, 0xf5, 0x68, 0x84, 0x5c, 0xc5, 0xa6, 0x35, 0xc9, 0xe7, 0x8c, 0xf6, 0x3f, 0x41,
	0x77, 0x26, 0xd4, 0x57, 0xa2, 0x52, 0x5e, 0x64, 0xa8, 0xca, 0x99, 0x0e, 0x06, 0x70, 0xaa, 0x58,
	0xc6, 0x45, 0xb1, 0x6f, 0xed, 0x37, 0xe2, 0xbf, 0x98, 0xff, 0x74, 0xc0, 0x47, 0x8b, 0xc9, 0x2d,
	0x51, 0x9c, 0x24, 0xc6, 0xfa, 0x0d, 0x80, 0x2a, 0x29, 0x6e, 0x9a, 0x0d, 0x9d, 0xde, 0xd1, 0xd0,
	0x1b, 0x3f, 0x89, 0x0e, 0x74, 0x1b, 0xb5, 0xcb, 0xcc, 0x65, 0x62, 0x4b, 0x90, 0xab, 0x4a, 0xda,
	0x1c, 0x2f, 0x26, 0xe0, 0xee, 0xf4, 0x20, 0x80, 0xe3, 0x82, 0xac, 0x59, 0xe8, 0xf4, 0x3a, 0x43,
	0x17, 0xd9, 0x73, 0xd0, 0xdf, 0x8f, 0xd8, 0xb1, 0x11, 0x3b, 0x57, 0x7b, 0x09, 0x7f, 0x74, 0xe0,
	0xec, 0x63, 0x95, 0xcc, 0xab, 0xe4, 0x1d, 0xd3, 0x9a, 0x64, 0x4c, 0x07, 0x0b, 0xf0, 0x75, 0x95,
	0x68, 0xaa, 0xb8, 0x2c, 0xb9, 0x28, 0x36, 0x29, 0x47, 0x07, 0x53, 0xee, 0x97, 0x46, 0xf3, 0x56,
	0x1d, 0xda, 0x73, 0x09, 0x2e, 0xc1, 0x27, 0x92, 0x63, 0x56, 0xa4, 0x52, 0xf0, 0xa2, 0xb4, 0x69,
	0x5c, 0xe4, 0x11, 0xc9, 0xa7, 0x1b, 0xe9, 0xe2, 0x3b, 0xf8, 0x6d, 0x83, 0x83, 0x3d, 0x3d, 0x04,
	0x28, 0x85, 0xe4, 0x14, 0xdb, 0x97, 0xc6, 0xc4, 0xb5, 0xca, 0x7b, 0xf3, 0xfc, 0x1c, 0x1e, 0x68,
	0xc6, 0x56, 0x38, 0x21, 0x74, 0x85, 0xd3, 0x4a, 0x11, 0x63, 0x64, 0xbb, 0x3f, 0xb2, 0xdd, 0x1f,
	0x5f, 0x3f, 0x1d, 0x8d, 0xd0, 0xb9, 0xf9, 0xf3, 0x82, 0xd0, 0xd5, 0xcb, 0xcd, 0x0f, 0x33, 0x89,
	0x5f, 0x66, 0x12, 0x4a, 0xd4, 0x3c, 0x65, 0x6a, 0x33, 0xd4, 0x10, 0xfe, 0x93, 0x4a, 0x7c, 0x61,
	0xb4, 0xb4, 0x43, 0x70, 0xd1, 0xf6, 0x1a, 0xcc, 0xe0, 0x34, 0xa3, 0x0c, 0xf3, 0x2d, 0x8c, 0x36,
	0x89, 0x37, 0xbe, 0x3c, 0x38, 0xa4, 0x36, 0xb5, 0xc8, 0xcf, 0x28, 0xbb, 0x63, 0xf8, 0x03, 0xfc,
	0xbf, 0xdc, 0xd1, 0x87, 0x95, 0xc1, 0xcf, 0x26, 0xf5, 0xc6, 0x8f, 0x0f, 0x5a, 0xdd, 0x43, 0x15,
	0x75, 0x97, 0xf7, 0xd8, 0x9d, 0xc1, 0xa9, 0x01, 0xac, 0xde, 0xa2, 0x13, 0x1e, 0xff, 0x21, 0x58,
	0x9b, 0x31, 0xe4, 0xab, 0x92, 0xde, 0x81, 0xfa, 0x16, 0xba, 0xb2, 0x4a, 0x74, 0x95, 0xe0, 0xf5,
	0x66, 0xb9, 0xe1, 0x89, 0x75, 0x1a, 0xfc, 0x05, 0x07, 0xe8, 0xac, 0xa9, 0xdd, 0x21, 0x35, 0x00,
	0xb3, 0x68, 0x5c, 0x33, 0xa5, 0x0d, 0x51, 0xd4, 0xac, 0xed, 0xa6, 0x53, 0x5f, 0x21, 0x20, 0x92,
	0xdf, 0x36, 0xea, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x44, 0xd9, 0x38, 0x2f, 0x04, 0x00,
	0x00,
}
