// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/targets/rds/server/gcp/proto/config.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	github.com/google/cloudprober/targets/rds/server/gcp/proto/config.proto

It has these top-level messages:
	GCEInstances
	RegionalForwardingRules
	ProviderConfig
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GCEInstances struct {
	// Zone filter, e.g. zone_filter: "us-east1-*" for all zones in us-east1
	// region.
	ZoneFilter       *string `protobuf:"bytes,1,opt,name=zone_filter,json=zoneFilter" json:"zone_filter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GCEInstances) Reset()                    { *m = GCEInstances{} }
func (m *GCEInstances) String() string            { return proto1.CompactTextString(m) }
func (*GCEInstances) ProtoMessage()               {}
func (*GCEInstances) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GCEInstances) GetZoneFilter() string {
	if m != nil && m.ZoneFilter != nil {
		return *m.ZoneFilter
	}
	return ""
}

type RegionalForwardingRules struct {
	// Region filter, e.g. "region_filter:europe-*"
	RegionFilter     *string `protobuf:"bytes,1,opt,name=region_filter,json=regionFilter" json:"region_filter,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegionalForwardingRules) Reset()                    { *m = RegionalForwardingRules{} }
func (m *RegionalForwardingRules) String() string            { return proto1.CompactTextString(m) }
func (*RegionalForwardingRules) ProtoMessage()               {}
func (*RegionalForwardingRules) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegionalForwardingRules) GetRegionFilter() string {
	if m != nil && m.RegionFilter != nil {
		return *m.RegionFilter
	}
	return ""
}

// GCP provider config.
type ProviderConfig struct {
	// GCP projects. If running on GCE, it defaults to the local project.
	Project []string `protobuf:"bytes,1,rep,name=project" json:"project,omitempty"`
	// GCE instances discovery options. This field should be declared for the GCE
	// instances discovery to be enabled.
	GceInstances *GCEInstances `protobuf:"bytes,2,opt,name=gce_instances,json=gceInstances" json:"gce_instances,omitempty"`
	// Regional forwarding rules discovery options. This field should be declared
	// for the regional forwarding rules discovery to be enabled.
	// NOTE: This is not supported yet.
	RegionalForwardingRules *RegionalForwardingRules `protobuf:"bytes,3,opt,name=regional_forwarding_rules,json=regionalForwardingRules" json:"regional_forwarding_rules,omitempty"`
	// How often targets should be evaluated/expanded
	ReEvalSec *int32 `protobuf:"varint,98,opt,name=re_eval_sec,json=reEvalSec,def=300" json:"re_eval_sec,omitempty"`
	// Compute API version.
	ApiVersion       *string `protobuf:"bytes,99,opt,name=api_version,json=apiVersion,def=v1" json:"api_version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProviderConfig) Reset()                    { *m = ProviderConfig{} }
func (m *ProviderConfig) String() string            { return proto1.CompactTextString(m) }
func (*ProviderConfig) ProtoMessage()               {}
func (*ProviderConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_ProviderConfig_ReEvalSec int32 = 300
const Default_ProviderConfig_ApiVersion string = "v1"

func (m *ProviderConfig) GetProject() []string {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *ProviderConfig) GetGceInstances() *GCEInstances {
	if m != nil {
		return m.GceInstances
	}
	return nil
}

func (m *ProviderConfig) GetRegionalForwardingRules() *RegionalForwardingRules {
	if m != nil {
		return m.RegionalForwardingRules
	}
	return nil
}

func (m *ProviderConfig) GetReEvalSec() int32 {
	if m != nil && m.ReEvalSec != nil {
		return *m.ReEvalSec
	}
	return Default_ProviderConfig_ReEvalSec
}

func (m *ProviderConfig) GetApiVersion() string {
	if m != nil && m.ApiVersion != nil {
		return *m.ApiVersion
	}
	return Default_ProviderConfig_ApiVersion
}

func init() {
	proto1.RegisterType((*GCEInstances)(nil), "cloudprober.targets.rds.gcp.GCEInstances")
	proto1.RegisterType((*RegionalForwardingRules)(nil), "cloudprober.targets.rds.gcp.RegionalForwardingRules")
	proto1.RegisterType((*ProviderConfig)(nil), "cloudprober.targets.rds.gcp.ProviderConfig")
}

func init() {
	proto1.RegisterFile("github.com/google/cloudprober/targets/rds/server/gcp/proto/config.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3d, 0x6f, 0xea, 0x30,
	0x14, 0x86, 0x15, 0xd0, 0xd5, 0x15, 0x06, 0xee, 0x90, 0x85, 0x5c, 0x75, 0x68, 0x44, 0x97, 0x74,
	0x89, 0xe9, 0xc7, 0xc4, 0xd0, 0x05, 0x01, 0xea, 0x52, 0x55, 0xae, 0xd4, 0x35, 0x32, 0xce, 0xc1,
	0x75, 0x95, 0xfa, 0x58, 0xc7, 0x26, 0x95, 0xfa, 0xc3, 0xfa, 0xfb, 0xaa, 0x04, 0x68, 0xe9, 0x00,
	0xe3, 0x79, 0xed, 0xf7, 0xe8, 0x79, 0x0e, 0x5b, 0x6a, 0x13, 0x5e, 0x36, 0xab, 0x5c, 0xe1, 0x1b,
	0xd7, 0x88, 0xba, 0x02, 0xae, 0x2a, 0xdc, 0x94, 0x8e, 0x70, 0x05, 0xc4, 0x83, 0x24, 0x0d, 0xc1,
	0x73, 0x2a, 0x3d, 0xf7, 0x40, 0x35, 0x10, 0xd7, 0xca, 0x71, 0x47, 0x18, 0x90, 0x2b, 0xb4, 0x6b,
	0xa3, 0xf3, 0x76, 0x88, 0xcf, 0x0e, 0x6a, 0xf9, 0xae, 0x96, 0x53, 0xe9, 0x73, 0xad, 0xdc, 0x98,
	0xb3, 0xc1, 0x72, 0x36, 0xbf, 0xb7, 0x3e, 0x48, 0xab, 0xc0, 0xc7, 0xe7, 0xac, 0xff, 0x81, 0x16,
	0x8a, 0xb5, 0xa9, 0x02, 0x50, 0x12, 0xa5, 0x51, 0xd6, 0x13, 0xac, 0x89, 0x16, 0x6d, 0x32, 0xbe,
	0x63, 0x23, 0x01, 0xda, 0xa0, 0x95, 0xd5, 0x02, 0xe9, 0x5d, 0x52, 0x69, 0xac, 0x16, 0x9b, 0x0a,
	0x7c, 0x7c, 0xc1, 0x86, 0xd4, 0x3e, 0xfd, 0x6e, 0x0f, 0xb6, 0xe1, 0xae, 0xff, 0xd9, 0x61, 0xff,
	0x1e, 0x09, 0x6b, 0x53, 0x02, 0xcd, 0x5a, 0xcc, 0x38, 0x61, 0x7f, 0x1d, 0xe1, 0x2b, 0xa8, 0x90,
	0x44, 0x69, 0x37, 0xeb, 0x89, 0xfd, 0x18, 0x3f, 0xb0, 0xa1, 0x56, 0x50, 0x98, 0x3d, 0x5e, 0xd2,
	0x49, 0xa3, 0xac, 0x7f, 0x7d, 0x99, 0x9f, 0x50, 0xca, 0x0f, 0x7d, 0xc4, 0x40, 0x2b, 0xf8, 0xb1,
	0x73, 0xec, 0x3f, 0xed, 0xe0, 0x8b, 0xf5, 0x37, 0x7d, 0x41, 0x0d, 0x7e, 0xd2, 0x6d, 0x77, 0xdf,
	0x9e, 0xdc, 0x7d, 0x44, 0x5d, 0x8c, 0xe8, 0xe8, 0x4d, 0xfa, 0x04, 0x05, 0xd4, 0xb2, 0x2a, 0x3c,
	0xa8, 0x64, 0x95, 0x46, 0xd9, 0x9f, 0x69, 0xf7, 0x66, 0x32, 0x11, 0x3d, 0x82, 0x79, 0x2d, 0xab,
	0x27, 0x50, 0xcd, 0x27, 0xe9, 0x4c, 0x51, 0x03, 0x79, 0x83, 0x36, 0x51, 0xcd, 0xd9, 0xa6, 0x9d,
	0xfa, 0x4a, 0x30, 0xe9, 0xcc, 0xf3, 0x36, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xe4, 0xfc,
	0xca, 0x10, 0x02, 0x00, 0x00,
}
