// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/servers/config.proto

/*
Package servers is a generated protocol buffer package.

It is generated from these files:
	github.com/google/cloudprober/servers/config.proto

It has these top-level messages:
	ServerDef
*/
package servers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import cloudprober_servers_http "github.com/google/cloudprober/servers/http"
import cloudprober_servers_udp "github.com/google/cloudprober/servers/udp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerDef_Type int32

const (
	ServerDef_HTTP ServerDef_Type = 0
	ServerDef_UDP  ServerDef_Type = 1
)

var ServerDef_Type_name = map[int32]string{
	0: "HTTP",
	1: "UDP",
}
var ServerDef_Type_value = map[string]int32{
	"HTTP": 0,
	"UDP":  1,
}

func (x ServerDef_Type) Enum() *ServerDef_Type {
	p := new(ServerDef_Type)
	*p = x
	return p
}
func (x ServerDef_Type) String() string {
	return proto.EnumName(ServerDef_Type_name, int32(x))
}
func (x *ServerDef_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerDef_Type_value, data, "ServerDef_Type")
	if err != nil {
		return err
	}
	*x = ServerDef_Type(value)
	return nil
}
func (ServerDef_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ServerDef struct {
	Type *ServerDef_Type `protobuf:"varint,1,req,name=type,enum=cloudprober.servers.ServerDef_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Server:
	//	*ServerDef_HttpServer
	//	*ServerDef_UdpServer
	Server           isServerDef_Server `protobuf_oneof:"server"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ServerDef) Reset()                    { *m = ServerDef{} }
func (m *ServerDef) String() string            { return proto.CompactTextString(m) }
func (*ServerDef) ProtoMessage()               {}
func (*ServerDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isServerDef_Server interface {
	isServerDef_Server()
}

type ServerDef_HttpServer struct {
	HttpServer *cloudprober_servers_http.ServerConf `protobuf:"bytes,2,opt,name=http_server,json=httpServer,oneof"`
}
type ServerDef_UdpServer struct {
	UdpServer *cloudprober_servers_udp.ServerConf `protobuf:"bytes,3,opt,name=udp_server,json=udpServer,oneof"`
}

func (*ServerDef_HttpServer) isServerDef_Server() {}
func (*ServerDef_UdpServer) isServerDef_Server()  {}

func (m *ServerDef) GetServer() isServerDef_Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *ServerDef) GetType() ServerDef_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ServerDef_HTTP
}

func (m *ServerDef) GetHttpServer() *cloudprober_servers_http.ServerConf {
	if x, ok := m.GetServer().(*ServerDef_HttpServer); ok {
		return x.HttpServer
	}
	return nil
}

func (m *ServerDef) GetUdpServer() *cloudprober_servers_udp.ServerConf {
	if x, ok := m.GetServer().(*ServerDef_UdpServer); ok {
		return x.UdpServer
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ServerDef) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ServerDef_OneofMarshaler, _ServerDef_OneofUnmarshaler, _ServerDef_OneofSizer, []interface{}{
		(*ServerDef_HttpServer)(nil),
		(*ServerDef_UdpServer)(nil),
	}
}

func _ServerDef_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ServerDef)
	// server
	switch x := m.Server.(type) {
	case *ServerDef_HttpServer:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HttpServer); err != nil {
			return err
		}
	case *ServerDef_UdpServer:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UdpServer); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ServerDef.Server has unexpected type %T", x)
	}
	return nil
}

func _ServerDef_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ServerDef)
	switch tag {
	case 2: // server.http_server
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(cloudprober_servers_http.ServerConf)
		err := b.DecodeMessage(msg)
		m.Server = &ServerDef_HttpServer{msg}
		return true, err
	case 3: // server.udp_server
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(cloudprober_servers_udp.ServerConf)
		err := b.DecodeMessage(msg)
		m.Server = &ServerDef_UdpServer{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ServerDef_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ServerDef)
	// server
	switch x := m.Server.(type) {
	case *ServerDef_HttpServer:
		s := proto.Size(x.HttpServer)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerDef_UdpServer:
		s := proto.Size(x.UdpServer)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ServerDef)(nil), "cloudprober.servers.ServerDef")
	proto.RegisterEnum("cloudprober.servers.ServerDef_Type", ServerDef_Type_name, ServerDef_Type_value)
}

func init() { proto.RegisterFile("github.com/google/cloudprober/servers/config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0x87, 0x97, 0xad, 0xe8, 0xf6, 0x06, 0x32, 0xe2, 0x65, 0xee, 0x34, 0xa6, 0x87, 0x9d, 0x12,
	0xe8, 0xc1, 0xdd, 0xb5, 0xe0, 0x8e, 0x63, 0xd6, 0xb3, 0xb0, 0x26, 0xcd, 0x0a, 0xb5, 0x2f, 0xa4,
	0x89, 0xd0, 0xff, 0xdc, 0xa3, 0xa4, 0x2d, 0xc5, 0x4a, 0x0f, 0xbd, 0xbe, 0xf7, 0xfd, 0x3e, 0x3e,
	0x08, 0x55, 0x66, 0xaf, 0xee, 0xc2, 0x12, 0xfc, 0xe2, 0x0a, 0x51, 0xe5, 0x92, 0x27, 0x39, 0x3a,
	0xa1, 0x0d, 0x5e, 0xa4, 0xe1, 0xa5, 0x34, 0xdf, 0xd2, 0x94, 0x3c, 0xc1, 0x22, 0xcd, 0x14, 0xd3,
	0x06, 0x2d, 0xd2, 0xfb, 0x3f, 0x04, 0x6b, 0x89, 0xcd, 0x61, 0x9c, 0xe8, 0x6a, 0xad, 0xee, 0xd9,
	0x36, 0xcf, 0xe3, 0x86, 0x4e, 0xf4, 0x77, 0xbb, 0x1f, 0x02, 0x8b, 0xf7, 0xfa, 0x19, 0xc9, 0x94,
	0x1e, 0x20, 0xb0, 0x95, 0x96, 0x6b, 0xb2, 0x9d, 0xee, 0xef, 0xc2, 0x47, 0x36, 0x90, 0xc8, 0x3a,
	0x9a, 0xc5, 0x95, 0x96, 0xe7, 0x7a, 0x40, 0xdf, 0x60, 0xe9, 0x9b, 0x3e, 0x1b, 0x68, 0x3d, 0xdd,
	0x92, 0xfd, 0x32, 0x7c, 0x1a, 0xdc, 0x7b, 0xae, 0x95, 0xbc, 0x62, 0x91, 0x1e, 0x27, 0x67, 0xf0,
	0xa7, 0xe6, 0x42, 0x23, 0x00, 0x27, 0x3a, 0xcf, 0xac, 0xf6, 0x0c, 0x77, 0x38, 0xf1, 0x4f, 0xb3,
	0x70, 0xa2, 0xb5, 0xec, 0x1e, 0x20, 0xf0, 0x71, 0x74, 0x0e, 0xc1, 0x31, 0x8e, 0x4f, 0xab, 0x09,
	0xbd, 0x85, 0xd9, 0x47, 0x74, 0x5a, 0x91, 0x97, 0x39, 0xdc, 0x34, 0x86, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xab, 0xbb, 0xa4, 0x87, 0xb5, 0x01, 0x00, 0x00,
}
