// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/targets/rds/proto/rds.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IPConfig_IPType int32

const (
	// Default IP of the resource.
	//  - Private IP for instance resource
	//  - Forwarding rule IP for forwarding rule.
	IPConfig_DEFAULT IPConfig_IPType = 0
	// Instance's external IP.
	IPConfig_PUBLIC IPConfig_IPType = 1
	// First IP address from the first Alias IP range. For example, for
	// alias IP range "192.168.12.0/24", 192.168.12.0 will be returned.
	// Supported only on GCE.
	IPConfig_ALIAS IPConfig_IPType = 2
)

var IPConfig_IPType_name = map[int32]string{
	0: "DEFAULT",
	1: "PUBLIC",
	2: "ALIAS",
}
var IPConfig_IPType_value = map[string]int32{
	"DEFAULT": 0,
	"PUBLIC":  1,
	"ALIAS":   2,
}

func (x IPConfig_IPType) Enum() *IPConfig_IPType {
	p := new(IPConfig_IPType)
	*p = x
	return p
}
func (x IPConfig_IPType) String() string {
	return proto.EnumName(IPConfig_IPType_name, int32(x))
}
func (x *IPConfig_IPType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(IPConfig_IPType_value, data, "IPConfig_IPType")
	if err != nil {
		return err
	}
	*x = IPConfig_IPType(value)
	return nil
}
func (IPConfig_IPType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rds_766f739e9b3d06d3, []int{2, 0}
}

type ListResourcesRequest struct {
	// Provider is the resource list provider, for example: "gcp", "aws", etc.
	Provider *string `protobuf:"bytes,1,req,name=provider" json:"provider,omitempty"`
	// Provider specific resource path. For example: for GCP, it could be
	// "gce_instances/<project>", "regional_forwarding_rules/<project>", etc.
	ResourcePath *string `protobuf:"bytes,2,opt,name=resource_path,json=resourcePath" json:"resource_path,omitempty"`
	// Filters for the resources list. Filters are ANDed: all filters should
	// succeed for an item to included in the result list.
	Filter []*Filter `protobuf:"bytes,3,rep,name=filter" json:"filter,omitempty"`
	// Optional. If resource has an IP (and a NIC) address, following
	// fields determine which IP address will be included in the results.
	IpConfig             *IPConfig `protobuf:"bytes,4,opt,name=ip_config,json=ipConfig" json:"ip_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListResourcesRequest) Reset()         { *m = ListResourcesRequest{} }
func (m *ListResourcesRequest) String() string { return proto.CompactTextString(m) }
func (*ListResourcesRequest) ProtoMessage()    {}
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rds_766f739e9b3d06d3, []int{0}
}
func (m *ListResourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResourcesRequest.Unmarshal(m, b)
}
func (m *ListResourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResourcesRequest.Marshal(b, m, deterministic)
}
func (dst *ListResourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResourcesRequest.Merge(dst, src)
}
func (m *ListResourcesRequest) XXX_Size() int {
	return xxx_messageInfo_ListResourcesRequest.Size(m)
}
func (m *ListResourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListResourcesRequest proto.InternalMessageInfo

func (m *ListResourcesRequest) GetProvider() string {
	if m != nil && m.Provider != nil {
		return *m.Provider
	}
	return ""
}

func (m *ListResourcesRequest) GetResourcePath() string {
	if m != nil && m.ResourcePath != nil {
		return *m.ResourcePath
	}
	return ""
}

func (m *ListResourcesRequest) GetFilter() []*Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListResourcesRequest) GetIpConfig() *IPConfig {
	if m != nil {
		return m.IpConfig
	}
	return nil
}

type Filter struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_rds_766f739e9b3d06d3, []int{1}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Filter) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type IPConfig struct {
	// NIC index
	NicIndex             *int32           `protobuf:"varint,1,opt,name=nic_index,json=nicIndex,def=0" json:"nic_index,omitempty"`
	IpType               *IPConfig_IPType `protobuf:"varint,3,opt,name=ip_type,json=ipType,enum=cloudprober.targets.rds.IPConfig_IPType" json:"ip_type,omitempty"`
	IpVersion            *int32           `protobuf:"varint,4,opt,name=ip_version,json=ipVersion,def=4" json:"ip_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IPConfig) Reset()         { *m = IPConfig{} }
func (m *IPConfig) String() string { return proto.CompactTextString(m) }
func (*IPConfig) ProtoMessage()    {}
func (*IPConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_rds_766f739e9b3d06d3, []int{2}
}
func (m *IPConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPConfig.Unmarshal(m, b)
}
func (m *IPConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPConfig.Marshal(b, m, deterministic)
}
func (dst *IPConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPConfig.Merge(dst, src)
}
func (m *IPConfig) XXX_Size() int {
	return xxx_messageInfo_IPConfig.Size(m)
}
func (m *IPConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IPConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IPConfig proto.InternalMessageInfo

const Default_IPConfig_NicIndex int32 = 0
const Default_IPConfig_IpVersion int32 = 4

func (m *IPConfig) GetNicIndex() int32 {
	if m != nil && m.NicIndex != nil {
		return *m.NicIndex
	}
	return Default_IPConfig_NicIndex
}

func (m *IPConfig) GetIpType() IPConfig_IPType {
	if m != nil && m.IpType != nil {
		return *m.IpType
	}
	return IPConfig_DEFAULT
}

func (m *IPConfig) GetIpVersion() int32 {
	if m != nil && m.IpVersion != nil {
		return *m.IpVersion
	}
	return Default_IPConfig_IpVersion
}

type Resource struct {
	// Resource name.
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// Resource's IP address, selected based on the request's ip_config.
	Ip *string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	// Id associated with the resource, if any.
	Id *string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	// Optional info associated with the resource. Some resource type may make use
	// of it.
	Info                 []byte   `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_rds_766f739e9b3d06d3, []int{3}
}
func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (dst *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(dst, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Resource) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *Resource) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Resource) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

type ListResourcesResponse struct {
	Resources            []*Resource `protobuf:"bytes,1,rep,name=resources" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResourcesResponse) Reset()         { *m = ListResourcesResponse{} }
func (m *ListResourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ListResourcesResponse) ProtoMessage()    {}
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rds_766f739e9b3d06d3, []int{4}
}
func (m *ListResourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResourcesResponse.Unmarshal(m, b)
}
func (m *ListResourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResourcesResponse.Marshal(b, m, deterministic)
}
func (dst *ListResourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResourcesResponse.Merge(dst, src)
}
func (m *ListResourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ListResourcesResponse.Size(m)
}
func (m *ListResourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResourcesResponse proto.InternalMessageInfo

func (m *ListResourcesResponse) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func init() {
	proto.RegisterType((*ListResourcesRequest)(nil), "cloudprober.targets.rds.ListResourcesRequest")
	proto.RegisterType((*Filter)(nil), "cloudprober.targets.rds.Filter")
	proto.RegisterType((*IPConfig)(nil), "cloudprober.targets.rds.IPConfig")
	proto.RegisterType((*Resource)(nil), "cloudprober.targets.rds.Resource")
	proto.RegisterType((*ListResourcesResponse)(nil), "cloudprober.targets.rds.ListResourcesResponse")
	proto.RegisterEnum("cloudprober.targets.rds.IPConfig_IPType", IPConfig_IPType_name, IPConfig_IPType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourceDiscoveryClient is the client API for ResourceDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceDiscoveryClient interface {
	// ListResources returns the list of resources matching the URI provided in
	// the request.
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
}

type resourceDiscoveryClient struct {
	cc *grpc.ClientConn
}

func NewResourceDiscoveryClient(cc *grpc.ClientConn) ResourceDiscoveryClient {
	return &resourceDiscoveryClient{cc}
}

func (c *resourceDiscoveryClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, "/cloudprober.targets.rds.ResourceDiscovery/ListResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceDiscoveryServer is the server API for ResourceDiscovery service.
type ResourceDiscoveryServer interface {
	// ListResources returns the list of resources matching the URI provided in
	// the request.
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
}

func RegisterResourceDiscoveryServer(s *grpc.Server, srv ResourceDiscoveryServer) {
	s.RegisterService(&_ResourceDiscovery_serviceDesc, srv)
}

func _ResourceDiscovery_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceDiscoveryServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudprober.targets.rds.ResourceDiscovery/ListResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceDiscoveryServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceDiscovery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloudprober.targets.rds.ResourceDiscovery",
	HandlerType: (*ResourceDiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListResources",
			Handler:    _ResourceDiscovery_ListResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/google/cloudprober/targets/rds/proto/rds.proto",
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/targets/rds/proto/rds.proto", fileDescriptor_rds_766f739e9b3d06d3)
}

var fileDescriptor_rds_766f739e9b3d06d3 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x14, 0xec, 0x3a, 0x4d, 0x1a, 0xbf, 0xb4, 0x55, 0x58, 0x15, 0x61, 0xf5, 0x00, 0xc6, 0x5c, 0x7c,
	0x00, 0xa7, 0x8a, 0x90, 0x10, 0x3d, 0x80, 0x42, 0x4b, 0x25, 0x4b, 0x39, 0x44, 0x4b, 0x8b, 0xb8,
	0x59, 0xae, 0xbd, 0x71, 0x9e, 0x48, 0xbd, 0xcb, 0xee, 0x3a, 0x22, 0x3f, 0x80, 0x9f, 0xc5, 0x7f,
	0xe0, 0x27, 0x21, 0xaf, 0x6d, 0xbe, 0x44, 0x04, 0x27, 0xcf, 0x1b, 0xcd, 0x3c, 0xcf, 0xd3, 0x2c,
	0xbc, 0x2c, 0xd0, 0xac, 0xaa, 0xdb, 0x28, 0x13, 0x77, 0x93, 0x42, 0x88, 0x62, 0xcd, 0x27, 0xd9,
	0x5a, 0x54, 0xb9, 0x54, 0xe2, 0x96, 0xab, 0x89, 0x49, 0x55, 0xc1, 0x8d, 0x9e, 0xa8, 0x5c, 0x4f,
	0xa4, 0x12, 0x46, 0xd4, 0x28, 0xb2, 0x88, 0x3e, 0xf8, 0x45, 0x18, 0xb5, 0xc2, 0x48, 0xe5, 0x3a,
	0xf8, 0x46, 0xe0, 0x64, 0x8e, 0xda, 0x30, 0xae, 0x45, 0xa5, 0x32, 0xae, 0x19, 0xff, 0x54, 0x71,
	0x6d, 0xe8, 0x29, 0x0c, 0xa5, 0x12, 0x1b, 0xcc, 0xb9, 0xf2, 0x88, 0xef, 0x84, 0x2e, 0xfb, 0x31,
	0xd3, 0x27, 0x70, 0xa4, 0x5a, 0x7d, 0x22, 0x53, 0xb3, 0xf2, 0x1c, 0x9f, 0x84, 0x2e, 0x3b, 0xec,
	0xc8, 0x45, 0x6a, 0x56, 0xf4, 0x05, 0x0c, 0x96, 0xb8, 0x36, 0x5c, 0x79, 0x3d, 0xbf, 0x17, 0x8e,
	0xa6, 0x8f, 0xa2, 0x1d, 0x19, 0xa2, 0x2b, 0x2b, 0x63, 0xad, 0x9c, 0xbe, 0x02, 0x17, 0x65, 0x92,
	0x89, 0x72, 0x89, 0x85, 0xb7, 0xef, 0x93, 0x70, 0x34, 0x7d, 0xbc, 0xd3, 0x1b, 0x2f, 0x2e, 0xac,
	0x90, 0x0d, 0x51, 0x36, 0x28, 0x38, 0x83, 0x41, 0xb3, 0x91, 0x8e, 0xa1, 0xf7, 0x91, 0x6f, 0xdb,
	0xf8, 0x35, 0xa4, 0x27, 0xd0, 0xdf, 0xa4, 0xeb, 0x8a, 0x7b, 0x8e, 0xe5, 0x9a, 0x21, 0xf8, 0x4a,
	0x60, 0xd8, 0x2d, 0xa2, 0x0f, 0xc1, 0x2d, 0x31, 0x4b, 0xb0, 0xcc, 0xf9, 0x67, 0x8f, 0xf8, 0x24,
	0xec, 0x9f, 0x93, 0x33, 0x36, 0x2c, 0x31, 0x8b, 0x6b, 0x8a, 0xce, 0xe0, 0x00, 0x65, 0x62, 0xb6,
	0x92, 0x7b, 0x3d, 0x9f, 0x84, 0xc7, 0xd3, 0xf0, 0x9f, 0xe1, 0xa2, 0x78, 0x71, 0xbd, 0x95, 0x9c,
	0x0d, 0x50, 0xd6, 0x5f, 0xea, 0x03, 0xa0, 0x4c, 0x36, 0x5c, 0x69, 0x14, 0xa5, 0x3d, 0xb1, 0x7f,
	0x4e, 0x9e, 0x33, 0x17, 0xe5, 0xfb, 0x86, 0x0b, 0x9e, 0xc2, 0xa0, 0xf1, 0xd0, 0x11, 0x1c, 0x5c,
	0xbe, 0xbd, 0x9a, 0xdd, 0xcc, 0xaf, 0xc7, 0x7b, 0x14, 0x60, 0xb0, 0xb8, 0x79, 0x33, 0x8f, 0x2f,
	0xc6, 0x84, 0xba, 0xd0, 0x9f, 0xcd, 0xe3, 0xd9, 0xbb, 0xb1, 0x13, 0x30, 0x18, 0x76, 0xfd, 0x51,
	0x0a, 0xfb, 0x65, 0x7a, 0xc7, 0xdb, 0xa3, 0x2d, 0xa6, 0xc7, 0xe0, 0xa0, 0x6c, 0x4b, 0x72, 0x50,
	0xda, 0x39, 0xb7, 0xe9, 0xeb, 0x39, 0xaf, 0x3d, 0x58, 0x2e, 0x85, 0x4d, 0x72, 0xc8, 0x2c, 0x0e,
	0x3e, 0xc0, 0xfd, 0x3f, 0xde, 0x85, 0x96, 0xa2, 0xd4, 0x9c, 0xbe, 0x06, 0xb7, 0xeb, 0x59, 0x7b,
	0xc4, 0x56, 0xbb, 0xbb, 0x9e, 0xce, 0xce, 0x7e, 0x7a, 0xa6, 0x5f, 0x08, 0xdc, 0xeb, 0xf8, 0x4b,
	0xd4, 0x99, 0xd8, 0x70, 0xb5, 0xa5, 0x12, 0x8e, 0x7e, 0xfb, 0x1f, 0x7d, 0xb6, 0x73, 0xe9, 0xdf,
	0xde, 0xeb, 0x69, 0xf4, 0xbf, 0xf2, 0xe6, 0x8c, 0x60, 0xef, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x1e, 0x2c, 0xed, 0x68, 0x4f, 0x03, 0x00, 0x00,
}
