// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/probes/dns/proto/config.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DNS query types from https://en.wikipedia.org/wiki/List_of_DNS_record_types
type QueryType int32

const (
	QueryType_NONE       QueryType = 0
	QueryType_A          QueryType = 1
	QueryType_NS         QueryType = 2
	QueryType_CNAME      QueryType = 5
	QueryType_SOA        QueryType = 6
	QueryType_PTR        QueryType = 12
	QueryType_MX         QueryType = 15
	QueryType_TXT        QueryType = 16
	QueryType_RP         QueryType = 17
	QueryType_AFSDB      QueryType = 18
	QueryType_SIG        QueryType = 24
	QueryType_KEY        QueryType = 25
	QueryType_AAAA       QueryType = 28
	QueryType_LOC        QueryType = 29
	QueryType_SRV        QueryType = 33
	QueryType_NAPTR      QueryType = 35
	QueryType_KX         QueryType = 36
	QueryType_CERT       QueryType = 37
	QueryType_DNAME      QueryType = 39
	QueryType_APL        QueryType = 42
	QueryType_DS         QueryType = 43
	QueryType_SSHFP      QueryType = 44
	QueryType_IPSECKEY   QueryType = 45
	QueryType_RRSIG      QueryType = 46
	QueryType_NSEC       QueryType = 47
	QueryType_DNSKEY     QueryType = 48
	QueryType_DHCID      QueryType = 49
	QueryType_NSEC3      QueryType = 50
	QueryType_NSEC3PARAM QueryType = 51
	QueryType_TLSA       QueryType = 52
	QueryType_HIP        QueryType = 55
	QueryType_CDS        QueryType = 59
	QueryType_CDNSKEY    QueryType = 60
	QueryType_OPENPGPKEY QueryType = 61
	QueryType_TKEY       QueryType = 249
	QueryType_TSIG       QueryType = 250
	QueryType_URI        QueryType = 256
	QueryType_CAA        QueryType = 257
	QueryType_TA         QueryType = 32768
	QueryType_DLV        QueryType = 32769
)

var QueryType_name = map[int32]string{
	0:     "NONE",
	1:     "A",
	2:     "NS",
	5:     "CNAME",
	6:     "SOA",
	12:    "PTR",
	15:    "MX",
	16:    "TXT",
	17:    "RP",
	18:    "AFSDB",
	24:    "SIG",
	25:    "KEY",
	28:    "AAAA",
	29:    "LOC",
	33:    "SRV",
	35:    "NAPTR",
	36:    "KX",
	37:    "CERT",
	39:    "DNAME",
	42:    "APL",
	43:    "DS",
	44:    "SSHFP",
	45:    "IPSECKEY",
	46:    "RRSIG",
	47:    "NSEC",
	48:    "DNSKEY",
	49:    "DHCID",
	50:    "NSEC3",
	51:    "NSEC3PARAM",
	52:    "TLSA",
	55:    "HIP",
	59:    "CDS",
	60:    "CDNSKEY",
	61:    "OPENPGPKEY",
	249:   "TKEY",
	250:   "TSIG",
	256:   "URI",
	257:   "CAA",
	32768: "TA",
	32769: "DLV",
}

var QueryType_value = map[string]int32{
	"NONE":       0,
	"A":          1,
	"NS":         2,
	"CNAME":      5,
	"SOA":        6,
	"PTR":        12,
	"MX":         15,
	"TXT":        16,
	"RP":         17,
	"AFSDB":      18,
	"SIG":        24,
	"KEY":        25,
	"AAAA":       28,
	"LOC":        29,
	"SRV":        33,
	"NAPTR":      35,
	"KX":         36,
	"CERT":       37,
	"DNAME":      39,
	"APL":        42,
	"DS":         43,
	"SSHFP":      44,
	"IPSECKEY":   45,
	"RRSIG":      46,
	"NSEC":       47,
	"DNSKEY":     48,
	"DHCID":      49,
	"NSEC3":      50,
	"NSEC3PARAM": 51,
	"TLSA":       52,
	"HIP":        55,
	"CDS":        59,
	"CDNSKEY":    60,
	"OPENPGPKEY": 61,
	"TKEY":       249,
	"TSIG":       250,
	"URI":        256,
	"CAA":        257,
	"TA":         32768,
	"DLV":        32769,
}

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}

func (x *QueryType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(QueryType_value, data, "QueryType")
	if err != nil {
		return err
	}
	*x = QueryType(value)
	return nil
}

func (QueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_31f4b71243c9f9dc, []int{0}
}

type ProbeConf struct {
	// Domain to use when making DNS queries
	ResolvedDomain *string `protobuf:"bytes,1,opt,name=resolved_domain,json=resolvedDomain,def=www.google.com." json:"resolved_domain,omitempty"`
	// DNS Query Type
	QueryType *QueryType `protobuf:"varint,3,opt,name=query_type,json=queryType,enum=cloudprober.probes.dns.QueryType,def=15" json:"query_type,omitempty"`
	// Minimum number of answers expected. Default behavior is to return success
	// if DNS response status is NOERROR.
	MinAnswers *uint32 `protobuf:"varint,4,opt,name=min_answers,json=minAnswers,def=0" json:"min_answers,omitempty"`
	// Whether to resolve the target before making the request. If set to false,
	// we hand over the target directly to the DNS client. Otherwise, we resolve
	// the target first to an IP address.
	ResolveFirst         *bool    `protobuf:"varint,5,opt,name=resolve_first,json=resolveFirst,def=0" json:"resolve_first,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeConf) Reset()         { *m = ProbeConf{} }
func (m *ProbeConf) String() string { return proto.CompactTextString(m) }
func (*ProbeConf) ProtoMessage()    {}
func (*ProbeConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_31f4b71243c9f9dc, []int{0}
}

func (m *ProbeConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeConf.Unmarshal(m, b)
}
func (m *ProbeConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeConf.Marshal(b, m, deterministic)
}
func (m *ProbeConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeConf.Merge(m, src)
}
func (m *ProbeConf) XXX_Size() int {
	return xxx_messageInfo_ProbeConf.Size(m)
}
func (m *ProbeConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeConf.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeConf proto.InternalMessageInfo

const Default_ProbeConf_ResolvedDomain string = "www.google.com."
const Default_ProbeConf_QueryType QueryType = QueryType_MX
const Default_ProbeConf_MinAnswers uint32 = 0
const Default_ProbeConf_ResolveFirst bool = false

func (m *ProbeConf) GetResolvedDomain() string {
	if m != nil && m.ResolvedDomain != nil {
		return *m.ResolvedDomain
	}
	return Default_ProbeConf_ResolvedDomain
}

func (m *ProbeConf) GetQueryType() QueryType {
	if m != nil && m.QueryType != nil {
		return *m.QueryType
	}
	return Default_ProbeConf_QueryType
}

func (m *ProbeConf) GetMinAnswers() uint32 {
	if m != nil && m.MinAnswers != nil {
		return *m.MinAnswers
	}
	return Default_ProbeConf_MinAnswers
}

func (m *ProbeConf) GetResolveFirst() bool {
	if m != nil && m.ResolveFirst != nil {
		return *m.ResolveFirst
	}
	return Default_ProbeConf_ResolveFirst
}

func init() {
	proto.RegisterEnum("cloudprober.probes.dns.QueryType", QueryType_name, QueryType_value)
	proto.RegisterType((*ProbeConf)(nil), "cloudprober.probes.dns.ProbeConf")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/probes/dns/proto/config.proto", fileDescriptor_31f4b71243c9f9dc)
}

var fileDescriptor_31f4b71243c9f9dc = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x5f, 0x8f, 0xd2, 0x5c,
	0x10, 0xc6, 0xdf, 0x96, 0x3f, 0x4b, 0x67, 0x59, 0x98, 0xf7, 0x5c, 0x18, 0x4c, 0x34, 0x61, 0x57,
	0x8d, 0x04, 0xb5, 0x5d, 0x77, 0x4d, 0x34, 0xac, 0x5e, 0x1c, 0xdb, 0xb2, 0x90, 0x85, 0x52, 0xcf,
	0xa9, 0x1b, 0xbc, 0x22, 0x2c, 0x14, 0x6c, 0x02, 0x2d, 0xdb, 0x82, 0x84, 0x3b, 0xf6, 0xbb, 0xf8,
	0xad, 0xfc, 0x24, 0x7a, 0x65, 0xa6, 0xb0, 0xc6, 0x0b, 0xaf, 0xfa, 0xcc, 0xcc, 0xef, 0x99, 0x67,
	0x7a, 0xe0, 0x62, 0x1a, 0x2c, 0xbf, 0xae, 0x6e, 0xf4, 0x51, 0x34, 0x37, 0xa6, 0x51, 0x34, 0x9d,
	0xf9, 0xc6, 0x68, 0x16, 0xad, 0xc6, 0x8b, 0x38, 0xba, 0xf1, 0x63, 0x23, 0xfd, 0x24, 0xc6, 0x38,
	0x4c, 0x48, 0x2e, 0x23, 0x63, 0x14, 0x85, 0x93, 0x60, 0xaa, 0xa7, 0x05, 0x7b, 0xf0, 0x17, 0xaa,
	0xef, 0x50, 0x7d, 0x1c, 0x26, 0x27, 0x3f, 0x14, 0xd0, 0x5c, 0x2a, 0xcd, 0x28, 0x9c, 0xb0, 0x77,
	0x50, 0x8e, 0xfd, 0x24, 0x9a, 0x7d, 0xf3, 0xc7, 0x83, 0x71, 0x34, 0x1f, 0x06, 0x61, 0x45, 0xa9,
	0x2a, 0x35, 0xad, 0x51, 0x5e, 0xaf, 0xd7, 0xfa, 0x2e, 0x94, 0xf2, 0x75, 0x51, 0xba, 0xe7, 0xac,
	0x14, 0x63, 0x16, 0xc0, 0xed, 0xca, 0x8f, 0x37, 0x83, 0xe5, 0x66, 0xe1, 0x57, 0x32, 0x55, 0xa5,
	0x56, 0x3a, 0x3b, 0xd6, 0xff, 0x1d, 0xaa, 0x7f, 0x22, 0xd2, 0xdb, 0x2c, 0xfc, 0x86, 0xda, 0xed,
	0x0b, 0xed, 0xf6, 0xbe, 0x64, 0x27, 0x70, 0x38, 0x0f, 0xc2, 0xc1, 0x30, 0x4c, 0xd6, 0x7e, 0x9c,
	0x54, 0xb2, 0x55, 0xa5, 0x76, 0xd4, 0x50, 0x4e, 0x05, 0xcc, 0x83, 0x90, 0xef, 0x9a, 0xac, 0x0e,
	0x47, 0xfb, 0xec, 0xc1, 0x24, 0x88, 0x93, 0x65, 0x25, 0x57, 0x55, 0x6a, 0x85, 0x46, 0x6e, 0x32,
	0x9c, 0x25, 0xbe, 0x28, 0xee, 0x67, 0x4d, 0x1a, 0xd5, 0xbf, 0x67, 0x40, 0xfb, 0x13, 0xc6, 0x0a,
	0x90, 0x75, 0x7a, 0x8e, 0x8d, 0xff, 0xb1, 0x1c, 0x28, 0x1c, 0x15, 0x96, 0x07, 0xd5, 0x91, 0xa8,
	0x32, 0x0d, 0x72, 0xa6, 0xc3, 0xbb, 0x36, 0xe6, 0xd8, 0x01, 0x64, 0x64, 0x8f, 0x63, 0x9e, 0x84,
	0xeb, 0x09, 0x2c, 0x12, 0xd4, 0xed, 0x63, 0x99, 0x1a, 0x5e, 0xdf, 0x43, 0xa4, 0x86, 0x70, 0xf1,
	0x7f, 0x72, 0xf1, 0xa6, 0xb4, 0x3e, 0x22, 0x4b, 0x5d, 0xed, 0x4b, 0xac, 0x90, 0xb8, 0xb2, 0xbf,
	0xe0, 0x43, 0xca, 0xe2, 0x9c, 0x73, 0x7c, 0x44, 0xad, 0x4e, 0xcf, 0xc4, 0xc7, 0x29, 0x24, 0xae,
	0xf1, 0x98, 0x8c, 0x0e, 0xa7, 0xe5, 0x4f, 0x68, 0xd7, 0x55, 0x1f, 0x9f, 0x12, 0x6e, 0xda, 0xc2,
	0xc3, 0x67, 0x34, 0xb4, 0xd2, 0x5b, 0x9e, 0x93, 0x81, 0xbb, 0x1d, 0xac, 0x13, 0x65, 0x49, 0x7c,
	0x41, 0x33, 0x29, 0x5b, 0x4d, 0x17, 0x5f, 0xb2, 0x22, 0x14, 0xda, 0xae, 0xb4, 0x4d, 0x4a, 0x7b,
	0x45, 0x03, 0x21, 0xe8, 0x02, 0x3d, 0xfd, 0x49, 0x69, 0x9b, 0x68, 0x30, 0x80, 0xbc, 0xe5, 0x48,
	0x02, 0x4e, 0xd3, 0xad, 0x2d, 0xb3, 0x6d, 0xe1, 0xeb, 0x34, 0x5d, 0xda, 0xe6, 0x39, 0x9e, 0xb1,
	0x12, 0x40, 0x2a, 0x5d, 0x2e, 0x78, 0x17, 0xcf, 0xc9, 0xeb, 0x75, 0x24, 0xc7, 0x37, 0x14, 0xdd,
	0x6a, 0xbb, 0xf8, 0x96, 0x84, 0x69, 0x49, 0xbc, 0x60, 0x87, 0x70, 0x60, 0xee, 0xd7, 0xbd, 0x27,
	0x63, 0xcf, 0xb5, 0x1d, 0xf7, 0xd2, 0xa5, 0xfa, 0x03, 0xd3, 0x20, 0xeb, 0x91, 0xfa, 0xa9, 0xa4,
	0x92, 0x2e, 0xf9, 0xa5, 0xb0, 0x02, 0x64, 0x3e, 0x8b, 0x36, 0x6e, 0x55, 0x52, 0x26, 0xe7, 0x78,
	0x47, 0x4a, 0xf5, 0x38, 0x6e, 0xb7, 0xf4, 0xe8, 0x19, 0xab, 0x73, 0x8d, 0x77, 0x5b, 0xf5, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xa0, 0x3e, 0xd6, 0xda, 0x02, 0x00, 0x00,
}
