// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/targets/rds/server/proto/config.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/google/cloudprober/targets/rds/server/gcp/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerConf struct {
	// List of providers that server supports.
	Provider             []*Provider `protobuf:"bytes,1,rep,name=provider" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerConf) Reset()         { *m = ServerConf{} }
func (m *ServerConf) String() string { return proto.CompactTextString(m) }
func (*ServerConf) ProtoMessage()    {}
func (*ServerConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a3234188f7c6305, []int{0}
}

func (m *ServerConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConf.Unmarshal(m, b)
}
func (m *ServerConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConf.Marshal(b, m, deterministic)
}
func (m *ServerConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConf.Merge(m, src)
}
func (m *ServerConf) XXX_Size() int {
	return xxx_messageInfo_ServerConf.Size(m)
}
func (m *ServerConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConf.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConf proto.InternalMessageInfo

func (m *ServerConf) GetProvider() []*Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type Provider struct {
	// Provider identifier, e.g. "gcp". Server routes incoming requests to various
	// providers based on this id.
	Id *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	// Types that are valid to be assigned to Config:
	//	*Provider_GcpConfig
	Config               isProvider_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a3234188f7c6305, []int{1}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type isProvider_Config interface {
	isProvider_Config()
}

type Provider_GcpConfig struct {
	GcpConfig *proto1.ProviderConfig `protobuf:"bytes,2,opt,name=gcp_config,json=gcpConfig,oneof"`
}

func (*Provider_GcpConfig) isProvider_Config() {}

func (m *Provider) GetConfig() isProvider_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Provider) GetGcpConfig() *proto1.ProviderConfig {
	if x, ok := m.GetConfig().(*Provider_GcpConfig); ok {
		return x.GcpConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Provider) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Provider_GcpConfig)(nil),
	}
}

func init() {
	proto.RegisterType((*ServerConf)(nil), "cloudprober.targets.rds.ServerConf")
	proto.RegisterType((*Provider)(nil), "cloudprober.targets.rds.Provider")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/targets/rds/server/proto/config.proto", fileDescriptor_4a3234188f7c6305)
}

var fileDescriptor_4a3234188f7c6305 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8e, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0xcd, 0x0a, 0x92, 0x9b, 0x03, 0x8b, 0x6d, 0x0c, 0x56, 0xf1, 0xaa, 0x80, 0xb0, 0x0b,
	0xd7, 0xdb, 0x98, 0x42, 0x41, 0x0b, 0x89, 0x3f, 0x40, 0xbc, 0xdd, 0xcd, 0xb8, 0x10, 0x33, 0xcb,
	0xec, 0x26, 0xbf, 0x5f, 0x48, 0x62, 0xb0, 0x30, 0xc5, 0x95, 0x6f, 0x78, 0xdf, 0xfb, 0x06, 0x6a,
	0xf4, 0xe9, 0x6b, 0x38, 0x29, 0x43, 0xdf, 0x1a, 0x89, 0xb0, 0x73, 0xda, 0x74, 0x34, 0xd8, 0xc0,
	0x74, 0x72, 0xac, 0xd3, 0x27, 0xa3, 0x4b, 0x51, 0xb3, 0x8d, 0x3a, 0x3a, 0x1e, 0x1d, 0xeb, 0xc0,
	0x94, 0x48, 0x1b, 0xea, 0x5b, 0x8f, 0x6a, 0x0a, 0xf2, 0xe6, 0x0f, 0xa2, 0x16, 0x44, 0xb1, 0x8d,
	0xb7, 0x4f, 0x67, 0xaf, 0xa3, 0x09, 0xff, 0x18, 0x0e, 0x2f, 0x00, 0xef, 0x53, 0xa1, 0xa6, 0xbe,
	0x95, 0x0f, 0x90, 0x07, 0xa6, 0xd1, 0x5b, 0xc7, 0x45, 0x56, 0x5e, 0x56, 0xfb, 0xe3, 0x9d, 0xda,
	0x78, 0x41, 0xbd, 0x2d, 0xc5, 0x66, 0x45, 0x0e, 0x0c, 0xf9, 0xef, 0x55, 0x5e, 0x83, 0xf0, 0xb6,
	0xc8, 0x4a, 0x51, 0xed, 0x1a, 0xe1, 0xad, 0x7c, 0x05, 0x40, 0x13, 0x3e, 0x66, 0x79, 0x21, 0xca,
	0xac, 0xda, 0x1f, 0xef, 0x37, 0xc7, 0xd1, 0x84, 0x55, 0x50, 0x4f, 0xc8, 0xf3, 0x45, 0xb3, 0x43,
	0x13, 0xe6, 0xf0, 0x98, 0xc3, 0xd5, 0xbc, 0xf4, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x30, 0xae,
	0xa0, 0x68, 0x01, 0x00, 0x00,
}
