// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/targets/rds/server/proto/config.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "github.com/google/cloudprober/targets/rds/server/gcp/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerConf struct {
	// List of providers that server supports.
	Provider []*Provider `protobuf:"bytes,1,rep,name=provider" json:"provider,omitempty"`
	// Listener address for RDS server.
	Addr                 *string  `protobuf:"bytes,2,opt,name=addr,def=:9314" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerConf) Reset()         { *m = ServerConf{} }
func (m *ServerConf) String() string { return proto.CompactTextString(m) }
func (*ServerConf) ProtoMessage()    {}
func (*ServerConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_6086fe3dcb84baf6, []int{0}
}
func (m *ServerConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConf.Unmarshal(m, b)
}
func (m *ServerConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConf.Marshal(b, m, deterministic)
}
func (dst *ServerConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConf.Merge(dst, src)
}
func (m *ServerConf) XXX_Size() int {
	return xxx_messageInfo_ServerConf.Size(m)
}
func (m *ServerConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConf.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConf proto.InternalMessageInfo

const Default_ServerConf_Addr string = ":9314"

func (m *ServerConf) GetProvider() []*Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *ServerConf) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return Default_ServerConf_Addr
}

type Provider struct {
	// Provider identifier, e.g. "gcp". Server routes incoming requests to various
	// providers based on this id.
	Id *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	// Types that are valid to be assigned to Config:
	//	*Provider_GcpConfig
	Config               isProvider_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_6086fe3dcb84baf6, []int{1}
}
func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (dst *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(dst, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type isProvider_Config interface {
	isProvider_Config()
}

type Provider_GcpConfig struct {
	GcpConfig *proto1.ProviderConfig `protobuf:"bytes,2,opt,name=gcp_config,json=gcpConfig,oneof"`
}

func (*Provider_GcpConfig) isProvider_Config() {}

func (m *Provider) GetConfig() isProvider_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Provider) GetGcpConfig() *proto1.ProviderConfig {
	if x, ok := m.GetConfig().(*Provider_GcpConfig); ok {
		return x.GcpConfig
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Provider) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Provider_OneofMarshaler, _Provider_OneofUnmarshaler, _Provider_OneofSizer, []interface{}{
		(*Provider_GcpConfig)(nil),
	}
}

func _Provider_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Provider)
	// config
	switch x := m.Config.(type) {
	case *Provider_GcpConfig:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GcpConfig); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Provider.Config has unexpected type %T", x)
	}
	return nil
}

func _Provider_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Provider)
	switch tag {
	case 2: // config.gcp_config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto1.ProviderConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Provider_GcpConfig{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Provider_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Provider)
	// config
	switch x := m.Config.(type) {
	case *Provider_GcpConfig:
		s := proto.Size(x.GcpConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ServerConf)(nil), "cloudprober.targets.rds.ServerConf")
	proto.RegisterType((*Provider)(nil), "cloudprober.targets.rds.Provider")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/targets/rds/server/proto/config.proto", fileDescriptor_config_6086fe3dcb84baf6)
}

var fileDescriptor_config_6086fe3dcb84baf6 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8e, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x49, 0xf8, 0xa3, 0xe4, 0x2a, 0x31, 0x78, 0x21, 0x30, 0x85, 0x4e, 0x91, 0x90, 0x6c,
	0x51, 0x58, 0xa8, 0xc4, 0x42, 0x06, 0x18, 0x18, 0x50, 0xf8, 0x00, 0xa8, 0xf5, 0x39, 0x87, 0xa5,
	0xd2, 0xb3, 0x2e, 0x6e, 0x3f, 0x3f, 0x92, 0x53, 0x2a, 0x06, 0x3a, 0x30, 0xde, 0xe9, 0xfd, 0xde,
	0xef, 0x41, 0x4b, 0x3e, 0x7e, 0x6e, 0x96, 0xda, 0xf2, 0x97, 0x21, 0x66, 0x5a, 0x39, 0x63, 0x57,
	0xbc, 0xc1, 0x20, 0xbc, 0x74, 0x62, 0xe2, 0x42, 0xc8, 0xc5, 0xc1, 0x08, 0x0e, 0x66, 0x70, 0xb2,
	0x75, 0x62, 0x82, 0x70, 0x64, 0x63, 0x79, 0xdd, 0x7b, 0xd2, 0xe9, 0x50, 0x17, 0xbf, 0x10, 0xbd,
	0x43, 0xb4, 0xe0, 0x70, 0xf5, 0xfc, 0xef, 0x76, 0xb2, 0xe1, 0x0f, 0xc3, 0xb4, 0x07, 0x78, 0x4f,
	0x81, 0x96, 0xd7, 0xbd, 0x7a, 0x84, 0x22, 0x08, 0x6f, 0x3d, 0x3a, 0xa9, 0xb2, 0xfa, 0xb8, 0x99,
	0xcc, 0xae, 0xf5, 0x81, 0x09, 0xfa, 0x6d, 0x17, 0xec, 0xf6, 0x88, 0xba, 0x84, 0x93, 0x05, 0xa2,
	0x54, 0x79, 0x9d, 0x35, 0xe5, 0xfc, 0x74, 0xfe, 0x70, 0x77, 0x7b, 0xdf, 0xa5, 0xd7, 0x54, 0xa0,
	0xf8, 0x01, 0xd4, 0x39, 0xe4, 0x1e, 0xab, 0xac, 0xce, 0x9b, 0xb2, 0xcb, 0x3d, 0xaa, 0x57, 0x00,
	0xb2, 0xe1, 0x63, 0xdc, 0x95, 0xe0, 0xc9, 0xec, 0xe6, 0xa0, 0x97, 0x6c, 0xd8, 0xbb, 0xdb, 0x84,
	0xbc, 0x1c, 0x75, 0x25, 0xd9, 0x30, 0x1e, 0x4f, 0x05, 0x9c, 0x8d, 0x4d, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x43, 0x16, 0x39, 0x6a, 0x83, 0x01, 0x00, 0x00,
}
