// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/targets/rds/server/proto/config.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	github.com/google/cloudprober/targets/rds/server/proto/config.proto

It has these top-level messages:
	ServerConf
	Provider
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import cloudprober_targets_rds_gcp "github.com/google/cloudprober/targets/rds/server/gcp/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerConf struct {
	Provider []*Provider `protobuf:"bytes,1,rep,name=provider" json:"provider,omitempty"`
	// Listener address for RDS server.
	Address          *string `protobuf:"bytes,2,opt,name=address,def=:9314" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerConf) Reset()                    { *m = ServerConf{} }
func (m *ServerConf) String() string            { return proto1.CompactTextString(m) }
func (*ServerConf) ProtoMessage()               {}
func (*ServerConf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_ServerConf_Address string = ":9314"

func (m *ServerConf) GetProvider() []*Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *ServerConf) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return Default_ServerConf_Address
}

type Provider struct {
	Id *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	// Types that are valid to be assigned to Config:
	//	*Provider_GcpConfig
	Config           isProvider_Config `protobuf_oneof:"config"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Provider) Reset()                    { *m = Provider{} }
func (m *Provider) String() string            { return proto1.CompactTextString(m) }
func (*Provider) ProtoMessage()               {}
func (*Provider) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isProvider_Config interface {
	isProvider_Config()
}

type Provider_GcpConfig struct {
	GcpConfig *cloudprober_targets_rds_gcp.ProviderConfig `protobuf:"bytes,2,opt,name=gcp_config,json=gcpConfig,oneof"`
}

func (*Provider_GcpConfig) isProvider_Config() {}

func (m *Provider) GetConfig() isProvider_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Provider) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Provider) GetGcpConfig() *cloudprober_targets_rds_gcp.ProviderConfig {
	if x, ok := m.GetConfig().(*Provider_GcpConfig); ok {
		return x.GcpConfig
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Provider) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _Provider_OneofMarshaler, _Provider_OneofUnmarshaler, _Provider_OneofSizer, []interface{}{
		(*Provider_GcpConfig)(nil),
	}
}

func _Provider_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*Provider)
	// config
	switch x := m.Config.(type) {
	case *Provider_GcpConfig:
		b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.GcpConfig); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Provider.Config has unexpected type %T", x)
	}
	return nil
}

func _Provider_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*Provider)
	switch tag {
	case 2: // config.gcp_config
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(cloudprober_targets_rds_gcp.ProviderConfig)
		err := b.DecodeMessage(msg)
		m.Config = &Provider_GcpConfig{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Provider_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*Provider)
	// config
	switch x := m.Config.(type) {
	case *Provider_GcpConfig:
		s := proto1.Size(x.GcpConfig)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto1.RegisterType((*ServerConf)(nil), "cloudprober.targets.rds.ServerConf")
	proto1.RegisterType((*Provider)(nil), "cloudprober.targets.rds.Provider")
}

func init() {
	proto1.RegisterFile("github.com/google/cloudprober/targets/rds/server/proto/config.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8e, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x44, 0x4d, 0xa6, 0xe0, 0x61, 0x2f, 0x06, 0x2f, 0xc6, 0x9e, 0x02, 0xc2, 0x2e,
	0x56, 0x2f, 0x16, 0xbc, 0x98, 0x83, 0x1e, 0x3c, 0x48, 0xfc, 0x01, 0xd2, 0xee, 0x6c, 0xc7, 0x85,
	0xd8, 0x59, 0x66, 0xd3, 0xfe, 0x7e, 0x21, 0x69, 0x8b, 0x07, 0x73, 0xe8, 0x71, 0x86, 0xf7, 0xbd,
	0xf7, 0x41, 0x4d, 0xbe, 0xfb, 0xde, 0x2c, 0xb5, 0xe5, 0x1f, 0x43, 0xcc, 0xd4, 0x3a, 0x63, 0x5b,
	0xde, 0x60, 0x10, 0x5e, 0x3a, 0x31, 0xdd, 0x42, 0xc8, 0x75, 0xd1, 0x08, 0x46, 0x13, 0x9d, 0x6c,
	0x9d, 0x98, 0x20, 0xdc, 0xb1, 0xb1, 0xbc, 0x5e, 0x79, 0xd2, 0xfd, 0xa1, 0xae, 0xfe, 0x20, 0x7a,
	0x87, 0x68, 0xc1, 0x78, 0xfd, 0x7a, 0x74, 0x3b, 0xd9, 0xf0, 0xcf, 0xc2, 0xb4, 0x05, 0xf8, 0xec,
	0x03, 0x35, 0xaf, 0x57, 0xea, 0x19, 0xb2, 0x20, 0xbc, 0xf5, 0xe8, 0xa4, 0x48, 0xca, 0xd3, 0x6a,
	0x32, 0xbb, 0xd5, 0x23, 0x0a, 0xfa, 0x63, 0x17, 0x6c, 0x0e, 0x88, 0xba, 0x81, 0x8b, 0x05, 0xa2,
	0xb8, 0x18, 0x8b, 0xb4, 0x4c, 0xaa, 0x7c, 0x7e, 0x36, 0x7f, 0x7a, 0xb8, 0x7f, 0x6c, 0xf6, 0xdf,
	0xa9, 0x40, 0xb6, 0xc7, 0xd4, 0x25, 0xa4, 0x1e, 0x8b, 0xa4, 0x4c, 0xab, 0xbc, 0x49, 0x3d, 0xaa,
	0x77, 0x00, 0xb2, 0xe1, 0x6b, 0xb0, 0xeb, 0xf9, 0xc9, 0xec, 0x6e, 0x74, 0x9d, 0x6c, 0x38, 0x18,
	0xd4, 0x3d, 0xf2, 0x76, 0xd2, 0xe4, 0x64, 0xc3, 0x70, 0xbc, 0x64, 0x70, 0x3e, 0x34, 0xfd, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xd2, 0x48, 0x18, 0xb5, 0x89, 0x01, 0x00, 0x00,
}
