// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/probes/http/config.proto

/*
Package http is a generated protocol buffer package.

It is generated from these files:
	github.com/google/cloudprober/probes/http/config.proto

It has these top-level messages:
	ProbeConf
*/
package http

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProbeConf_ProtocolType int32

const (
	ProbeConf_HTTP  ProbeConf_ProtocolType = 0
	ProbeConf_HTTPS ProbeConf_ProtocolType = 1
)

var ProbeConf_ProtocolType_name = map[int32]string{
	0: "HTTP",
	1: "HTTPS",
}
var ProbeConf_ProtocolType_value = map[string]int32{
	"HTTP":  0,
	"HTTPS": 1,
}

func (x ProbeConf_ProtocolType) Enum() *ProbeConf_ProtocolType {
	p := new(ProbeConf_ProtocolType)
	*p = x
	return p
}
func (x ProbeConf_ProtocolType) String() string {
	return proto.EnumName(ProbeConf_ProtocolType_name, int32(x))
}
func (x *ProbeConf_ProtocolType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProbeConf_ProtocolType_value, data, "ProbeConf_ProtocolType")
	if err != nil {
		return err
	}
	*x = ProbeConf_ProtocolType(value)
	return nil
}
func (ProbeConf_ProtocolType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ProbeConf struct {
	// Which HTTP protocol to use
	Protocol *ProbeConf_ProtocolType `protobuf:"varint,1,opt,name=protocol,enum=cloudprober.probes.http.ProbeConf_ProtocolType,def=0" json:"protocol,omitempty"`
	// Relative URL (to append to all targets). Must begin with '/'
	RelativeUrl *string `protobuf:"bytes,2,opt,name=relative_url,json=relativeUrl" json:"relative_url,omitempty"`
	// Port, default is 80 for HTTP and 443 for HTTPS
	Port *int32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	// Whether to resolve the target before making the request. If set to false,
	// we hand over the target and relative_url directly to the golang's HTTP
	// module, Otherwise, we resolve the target first to an IP address and
	// make a request using that while passing target name as Host header.
	ResolveFirst *bool `protobuf:"varint,4,opt,name=resolve_first,json=resolveFirst,def=0" json:"resolve_first,omitempty"`
	// Export response (body) count as a metric
	ExportResponseAsMetrics *bool `protobuf:"varint,5,opt,name=export_response_as_metrics,json=exportResponseAsMetrics,def=0" json:"export_response_as_metrics,omitempty"`
	// Requests per probe
	RequestsPerProbe *int32 `protobuf:"varint,98,opt,name=requests_per_probe,json=requestsPerProbe,def=1" json:"requests_per_probe,omitempty"`
	// How long to wait between two requests to the same target
	RequestsIntervalMsec *int32 `protobuf:"varint,99,opt,name=requests_interval_msec,json=requestsIntervalMsec,def=25" json:"requests_interval_msec,omitempty"`
	// Export stats after these many milliseconds
	StatsExportIntervalMsec *int32 `protobuf:"varint,100,opt,name=stats_export_interval_msec,json=statsExportIntervalMsec,def=10000" json:"stats_export_interval_msec,omitempty"`
	XXX_unrecognized        []byte `json:"-"`
}

func (m *ProbeConf) Reset()                    { *m = ProbeConf{} }
func (m *ProbeConf) String() string            { return proto.CompactTextString(m) }
func (*ProbeConf) ProtoMessage()               {}
func (*ProbeConf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_ProbeConf_Protocol ProbeConf_ProtocolType = ProbeConf_HTTP
const Default_ProbeConf_ResolveFirst bool = false
const Default_ProbeConf_ExportResponseAsMetrics bool = false
const Default_ProbeConf_RequestsPerProbe int32 = 1
const Default_ProbeConf_RequestsIntervalMsec int32 = 25
const Default_ProbeConf_StatsExportIntervalMsec int32 = 10000

func (m *ProbeConf) GetProtocol() ProbeConf_ProtocolType {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return Default_ProbeConf_Protocol
}

func (m *ProbeConf) GetRelativeUrl() string {
	if m != nil && m.RelativeUrl != nil {
		return *m.RelativeUrl
	}
	return ""
}

func (m *ProbeConf) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *ProbeConf) GetResolveFirst() bool {
	if m != nil && m.ResolveFirst != nil {
		return *m.ResolveFirst
	}
	return Default_ProbeConf_ResolveFirst
}

func (m *ProbeConf) GetExportResponseAsMetrics() bool {
	if m != nil && m.ExportResponseAsMetrics != nil {
		return *m.ExportResponseAsMetrics
	}
	return Default_ProbeConf_ExportResponseAsMetrics
}

func (m *ProbeConf) GetRequestsPerProbe() int32 {
	if m != nil && m.RequestsPerProbe != nil {
		return *m.RequestsPerProbe
	}
	return Default_ProbeConf_RequestsPerProbe
}

func (m *ProbeConf) GetRequestsIntervalMsec() int32 {
	if m != nil && m.RequestsIntervalMsec != nil {
		return *m.RequestsIntervalMsec
	}
	return Default_ProbeConf_RequestsIntervalMsec
}

func (m *ProbeConf) GetStatsExportIntervalMsec() int32 {
	if m != nil && m.StatsExportIntervalMsec != nil {
		return *m.StatsExportIntervalMsec
	}
	return Default_ProbeConf_StatsExportIntervalMsec
}

func init() {
	proto.RegisterType((*ProbeConf)(nil), "cloudprober.probes.http.ProbeConf")
	proto.RegisterEnum("cloudprober.probes.http.ProbeConf_ProtocolType", ProbeConf_ProtocolType_name, ProbeConf_ProtocolType_value)
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/probes/http/config.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x1d, 0xb0, 0x04, 0x2a, 0x1a, 0xd2, 0x18, 0x59, 0x3c, 0x4d, 0xbc, 0x2c, 0x1e, 0xb6,
	0x41, 0xa2, 0x31, 0xdc, 0xd4, 0x68, 0xf4, 0x40, 0x82, 0x15, 0xcf, 0xcd, 0x28, 0x6f, 0x63, 0x49,
	0x59, 0x67, 0xdb, 0x11, 0xfd, 0xa8, 0x7e, 0x1b, 0xd3, 0x32, 0xc8, 0x3c, 0x78, 0xda, 0x5b, 0xdf,
	0xef, 0xf7, 0xf2, 0x7f, 0x0f, 0xdd, 0x66, 0xb9, 0x5e, 0x57, 0xcb, 0x90, 0x89, 0x4d, 0x94, 0x09,
	0x91, 0x71, 0x88, 0x18, 0x17, 0xd5, 0xaa, 0x94, 0x62, 0x09, 0x32, 0xb2, 0x1f, 0x15, 0xad, 0xb5,
	0x2e, 0x23, 0x26, 0x8a, 0x34, 0xcf, 0xc2, 0x52, 0x0a, 0x2d, 0xf0, 0xb0, 0x41, 0x85, 0x3b, 0x2a,
	0x34, 0xd4, 0xe8, 0xa7, 0x8d, 0x7a, 0x73, 0xf3, 0xff, 0x28, 0x8a, 0x14, 0xbf, 0xa1, 0xae, 0xe5,
	0x99, 0xe0, 0x9e, 0xe3, 0x3b, 0xc1, 0xe9, 0x24, 0x0a, 0xff, 0x31, 0xc3, 0x83, 0x65, 0x2a, 0xab,
	0x2c, 0xbe, 0x4b, 0x98, 0x76, 0x5e, 0x16, 0x8b, 0x39, 0x39, 0x8c, 0xc1, 0x97, 0xa8, 0x2f, 0x81,
	0x27, 0x3a, 0xdf, 0x02, 0xad, 0x24, 0xf7, 0x5a, 0xbe, 0x13, 0xf4, 0xc8, 0xf1, 0xfe, 0xed, 0x43,
	0x72, 0x8c, 0x51, 0xa7, 0x14, 0x52, 0x7b, 0x6d, 0xdf, 0x09, 0x5c, 0x62, 0x6b, 0x7c, 0x8d, 0x4e,
	0x24, 0x28, 0xc1, 0xb7, 0x40, 0xd3, 0x5c, 0x2a, 0xed, 0x75, 0x7c, 0x27, 0xe8, 0x4e, 0xdd, 0x34,
	0xe1, 0x0a, 0x48, 0xbf, 0xee, 0x3d, 0x9b, 0x16, 0x7e, 0x40, 0x17, 0xf0, 0x65, 0x2c, 0x2a, 0x41,
	0x95, 0xa2, 0x50, 0x40, 0x13, 0x45, 0x37, 0xa0, 0x65, 0xce, 0x94, 0xe7, 0x36, 0xc5, 0xe1, 0x0e,
	0x24, 0x35, 0x77, 0xaf, 0x66, 0x3b, 0x0a, 0x47, 0x08, 0x4b, 0xf8, 0xac, 0x40, 0x69, 0x45, 0x4b,
	0x90, 0xd4, 0x6e, 0xea, 0x2d, 0x4d, 0xa2, 0xa9, 0x33, 0x26, 0x83, 0x7d, 0x73, 0x0e, 0xd2, 0x2e,
	0x8e, 0xef, 0xd0, 0xf9, 0x41, 0xc8, 0x0b, 0x0d, 0x72, 0x9b, 0x70, 0xba, 0x51, 0xc0, 0x3c, 0x66,
	0xa5, 0xd6, 0xe4, 0x86, 0x9c, 0xed, 0x89, 0xd7, 0x1a, 0x98, 0x29, 0x60, 0x26, 0xae, 0xd2, 0x89,
	0x56, 0xb4, 0x0e, 0xfd, 0xd7, 0x5e, 0x59, 0xdb, 0x1d, 0xc7, 0x71, 0x1c, 0x93, 0xa1, 0x05, 0x9f,
	0x2c, 0xd7, 0x9c, 0x31, 0xba, 0x42, 0xfd, 0xe6, 0xd5, 0x71, 0x17, 0xd9, 0xbb, 0x0f, 0x8e, 0x70,
	0x0f, 0xb9, 0xa6, 0x7a, 0x1f, 0x38, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x17, 0xb6, 0x4d,
	0x2d, 0x02, 0x00, 0x00,
}
