// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/message/proto/message.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	github.com/google/cloudprober/message/proto/message.proto

It has these top-level messages:
	Constants
	DataNode
	Msg
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type DataNode_Type int32

const (
	DataNode_UNKNOWN DataNode_Type = 0
	DataNode_CLIENT  DataNode_Type = 1
	DataNode_SERVER  DataNode_Type = 2
)

var DataNode_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "CLIENT",
	2: "SERVER",
}
var DataNode_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"CLIENT":  1,
	"SERVER":  2,
}

func (x DataNode_Type) Enum() *DataNode_Type {
	p := new(DataNode_Type)
	*p = x
	return p
}
func (x DataNode_Type) String() string {
	return proto1.EnumName(DataNode_Type_name, int32(x))
}
func (x *DataNode_Type) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(DataNode_Type_value, data, "DataNode_Type")
	if err != nil {
		return err
	}
	*x = DataNode_Type(value)
	return nil
}
func (DataNode_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// Constants defines constants with default values.
type Constants struct {
	Magic            *uint64 `protobuf:"varint,1,opt,name=magic,def=257787339638762" json:"magic,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Constants) Reset()                    { *m = Constants{} }
func (m *Constants) String() string            { return proto1.CompactTextString(m) }
func (*Constants) ProtoMessage()               {}
func (*Constants) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Constants_Magic uint64 = 257787339638762

func (m *Constants) GetMagic() uint64 {
	if m != nil && m.Magic != nil {
		return *m.Magic
	}
	return Default_Constants_Magic
}

// Datanode is something that see's a message AND can modify it.
type DataNode struct {
	Type *DataNode_Type `protobuf:"varint,1,opt,name=type,enum=message.DataNode_Type,def=1" json:"type,omitempty"`
	Name *string        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Port *string        `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	// 8 bytes of timestamp in pcap-friendly network byte order.
	TimestampUsec    []byte `protobuf:"bytes,3,opt,name=timestamp_usec,json=timestampUsec" json:"timestamp_usec,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DataNode) Reset()                    { *m = DataNode{} }
func (m *DataNode) String() string            { return proto1.CompactTextString(m) }
func (*DataNode) ProtoMessage()               {}
func (*DataNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_DataNode_Type DataNode_Type = DataNode_CLIENT

func (m *DataNode) GetType() DataNode_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_DataNode_Type
}

func (m *DataNode) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *DataNode) GetPort() string {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return ""
}

func (m *DataNode) GetTimestampUsec() []byte {
	if m != nil {
		return m.TimestampUsec
	}
	return nil
}

// Msg is a message sent over the network.
// magic, seq, src and dst are required fields.
type Msg struct {
	Magic *uint64 `protobuf:"fixed64,1,opt,name=magic" json:"magic,omitempty"`
	// 8 bytes of sequence in pcap-friendly network byte order.
	Seq []byte `protobuf:"bytes,2,opt,name=seq" json:"seq,omitempty"`
	// Datanodes seen by this message.
	Src              *DataNode   `protobuf:"bytes,3,opt,name=src" json:"src,omitempty"`
	Dst              *DataNode   `protobuf:"bytes,4,opt,name=dst" json:"dst,omitempty"`
	Nodes            []*DataNode `protobuf:"bytes,5,rep,name=nodes" json:"nodes,omitempty"`
	Pad              []byte      `protobuf:"bytes,99,opt,name=pad" json:"pad,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto1.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Msg) GetMagic() uint64 {
	if m != nil && m.Magic != nil {
		return *m.Magic
	}
	return 0
}

func (m *Msg) GetSeq() []byte {
	if m != nil {
		return m.Seq
	}
	return nil
}

func (m *Msg) GetSrc() *DataNode {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *Msg) GetDst() *DataNode {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *Msg) GetNodes() []*DataNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Msg) GetPad() []byte {
	if m != nil {
		return m.Pad
	}
	return nil
}

func init() {
	proto1.RegisterType((*Constants)(nil), "message.Constants")
	proto1.RegisterType((*DataNode)(nil), "message.DataNode")
	proto1.RegisterType((*Msg)(nil), "message.Msg")
	proto1.RegisterEnum("message.DataNode_Type", DataNode_Type_name, DataNode_Type_value)
}

func init() {
	proto1.RegisterFile("github.com/google/cloudprober/message/proto/message.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x4f, 0x41, 0x6b, 0xea, 0x40,
	0x18, 0x7c, 0x6b, 0xa2, 0x3e, 0x3f, 0x7d, 0xbe, 0xbc, 0xe5, 0x51, 0x72, 0x0c, 0x29, 0x52, 0xa1,
	0x90, 0x40, 0xa4, 0x46, 0xbd, 0x5a, 0x0f, 0xa5, 0x6d, 0x0a, 0x5b, 0x6d, 0x8f, 0x65, 0xcd, 0x2e,
	0xa9, 0x60, 0xb2, 0xdb, 0xec, 0x7a, 0xf0, 0x6f, 0xf5, 0xd8, 0x5f, 0x57, 0x36, 0xd1, 0x52, 0xa8,
	0xb7, 0xf9, 0x66, 0xe6, 0x63, 0x66, 0x60, 0x9a, 0x6d, 0xf4, 0xeb, 0x6e, 0x1d, 0xa4, 0x22, 0x0f,
	0x33, 0x21, 0xb2, 0x2d, 0x0f, 0xd3, 0xad, 0xd8, 0x31, 0x59, 0x8a, 0x35, 0x2f, 0xc3, 0x9c, 0x2b,
	0x45, 0x33, 0x1e, 0xca, 0x52, 0x68, 0x71, 0xbc, 0x82, 0xea, 0xc2, 0xed, 0xc3, 0xe9, 0x47, 0xd0,
	0x99, 0x8b, 0x42, 0x69, 0x5a, 0x68, 0x85, 0x07, 0xd0, 0xcc, 0x69, 0xb6, 0x49, 0x5d, 0xe4, 0xa1,
	0xa1, 0x3d, 0xfb, 0x1b, 0x5d, 0xc5, 0xf1, 0x24, 0x1e, 0x8d, 0xa6, 0xe3, 0xd1, 0x24, 0x1e, 0x47,
	0xa4, 0x56, 0xfd, 0x0f, 0x04, 0xbf, 0xaf, 0xa9, 0xa6, 0x89, 0x60, 0x1c, 0x47, 0x60, 0xeb, 0xbd,
	0xe4, 0xd5, 0x4b, 0x3f, 0x3a, 0x0b, 0x8e, 0x39, 0x47, 0x43, 0xb0, 0xdc, 0x4b, 0x3e, 0x6b, 0xcd,
	0xef, 0x6e, 0x16, 0xc9, 0x92, 0x54, 0x5e, 0x8c, 0xc1, 0x2e, 0x68, 0xce, 0xdd, 0x86, 0x87, 0x86,
	0x1d, 0x52, 0x61, 0xc3, 0x49, 0x51, 0x6a, 0xd7, 0xae, 0x39, 0x83, 0xf1, 0x00, 0xfa, 0x7a, 0x93,
	0x73, 0xa5, 0x69, 0x2e, 0x5f, 0x76, 0x8a, 0xa7, 0xae, 0xe5, 0xa1, 0x61, 0x8f, 0xfc, 0xf9, 0x62,
	0x57, 0x8a, 0xa7, 0xfe, 0x25, 0xd8, 0x26, 0x04, 0x77, 0xa1, 0xbd, 0x4a, 0x6e, 0x93, 0x87, 0xe7,
	0xc4, 0xf9, 0x85, 0x01, 0x0e, 0x99, 0x0e, 0x32, 0xf8, 0x71, 0x41, 0x9e, 0x16, 0xc4, 0x69, 0xf8,
	0xef, 0x08, 0xac, 0x7b, 0x95, 0xe1, 0xff, 0xdf, 0xb7, 0xb6, 0x0e, 0xd3, 0xb0, 0x03, 0x96, 0xe2,
	0x6f, 0x55, 0xb1, 0x1e, 0x31, 0x10, 0x9f, 0x83, 0xa5, 0xca, 0x3a, 0xb8, 0x1b, 0xfd, 0xfb, 0x31,
	0x8f, 0x18, 0xd5, 0x98, 0x98, 0xaa, 0xbb, 0x9f, 0x36, 0x31, 0xa5, 0xf1, 0x05, 0x34, 0x0b, 0xc1,
	0xb8, 0x72, 0x9b, 0x9e, 0x75, 0xda, 0x56, 0xeb, 0xa6, 0x84, 0xa4, 0xcc, 0x4d, 0xeb, 0x12, 0x92,
	0xb2, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0x42, 0xa4, 0xc8, 0xea, 0x01, 0x00, 0x00,
}
