// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/targets/rds/client/proto/config.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "github.com/google/cloudprober/targets/rds/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ClientConf represents resource discovery service (RDS) based targets.
// Next tag: 5
type ClientConf struct {
	ServerAddr *string `protobuf:"bytes,1,opt,name=server_addr,json=serverAddr,def=localhost:9314" json:"server_addr,omitempty"`
	// If tls_cert_file is provided, client uses the cert from that file to
	// authenticate itself to the RDS server.
	TlsCertFile *string                      `protobuf:"bytes,4,opt,name=tls_cert_file,json=tlsCertFile" json:"tls_cert_file,omitempty"`
	Request     *proto1.ListResourcesRequest `protobuf:"bytes,2,req,name=request" json:"request,omitempty"`
	// How often targets should be evaluated. Any number less than or equal to 0
	// will result in no target caching (targets will be reevaluated on demand).
	// Note that individual target types may have their own caches implemented
	// (specifically GCE instances/forwarding rules). This does not impact those
	// caches.
	ReEvalSec            *int32   `protobuf:"varint,3,opt,name=re_eval_sec,json=reEvalSec,def=30" json:"re_eval_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientConf) Reset()         { *m = ClientConf{} }
func (m *ClientConf) String() string { return proto.CompactTextString(m) }
func (*ClientConf) ProtoMessage()    {}
func (*ClientConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_7e7cf582f9f456e4, []int{0}
}
func (m *ClientConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConf.Unmarshal(m, b)
}
func (m *ClientConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConf.Marshal(b, m, deterministic)
}
func (dst *ClientConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConf.Merge(dst, src)
}
func (m *ClientConf) XXX_Size() int {
	return xxx_messageInfo_ClientConf.Size(m)
}
func (m *ClientConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConf.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConf proto.InternalMessageInfo

const Default_ClientConf_ServerAddr string = "localhost:9314"
const Default_ClientConf_ReEvalSec int32 = 30

func (m *ClientConf) GetServerAddr() string {
	if m != nil && m.ServerAddr != nil {
		return *m.ServerAddr
	}
	return Default_ClientConf_ServerAddr
}

func (m *ClientConf) GetTlsCertFile() string {
	if m != nil && m.TlsCertFile != nil {
		return *m.TlsCertFile
	}
	return ""
}

func (m *ClientConf) GetRequest() *proto1.ListResourcesRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ClientConf) GetReEvalSec() int32 {
	if m != nil && m.ReEvalSec != nil {
		return *m.ReEvalSec
	}
	return Default_ClientConf_ReEvalSec
}

func init() {
	proto.RegisterType((*ClientConf)(nil), "cloudprober.targets.rds.ClientConf")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/targets/rds/client/proto/config.proto", fileDescriptor_config_7e7cf582f9f456e4)
}

var fileDescriptor_config_7e7cf582f9f456e4 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xcf, 0xb1, 0x4a, 0xf4, 0x40,
	0x10, 0xc0, 0x71, 0x72, 0xdf, 0x27, 0x72, 0x1b, 0xb4, 0x48, 0x63, 0xb0, 0x0a, 0xa9, 0xd2, 0xb8,
	0xab, 0x9e, 0xcd, 0xa5, 0x93, 0xa0, 0x36, 0x56, 0xeb, 0x03, 0x84, 0xdc, 0xee, 0x24, 0xb7, 0xb0,
	0x66, 0xce, 0x99, 0x49, 0x1e, 0xd3, 0x67, 0x12, 0x2f, 0x0a, 0x36, 0x82, 0xe5, 0xc0, 0xfc, 0xfe,
	0xc3, 0xa8, 0x66, 0x08, 0xb2, 0x9f, 0x76, 0xda, 0xe1, 0xab, 0x19, 0x10, 0x87, 0x08, 0xc6, 0x45,
	0x9c, 0xfc, 0x81, 0x70, 0x07, 0x64, 0xa4, 0xa3, 0x01, 0x84, 0x0d, 0x79, 0x36, 0x2e, 0x06, 0x18,
	0xc5, 0x1c, 0x08, 0x05, 0x8d, 0xc3, 0xb1, 0x0f, 0x83, 0x3e, 0x0e, 0xd9, 0xc5, 0x0f, 0xa2, 0xbf,
	0x88, 0x26, 0xcf, 0x97, 0xdb, 0xbf, 0xd7, 0x97, 0x2c, 0x79, 0x5e, 0x9a, 0xe5, 0x7b, 0xa2, 0x54,
	0x73, 0xbc, 0xd8, 0xe0, 0xd8, 0x67, 0x46, 0xa5, 0x0c, 0x34, 0x03, 0xb5, 0x9d, 0xf7, 0x94, 0x27,
	0x45, 0x52, 0xad, 0xeb, 0xf3, 0x88, 0xae, 0x8b, 0x7b, 0x64, 0xa9, 0xb7, 0x9b, 0x9b, 0x3b, 0xab,
	0x96, 0x95, 0x7b, 0xef, 0x29, 0x2b, 0xd5, 0x99, 0x44, 0x6e, 0x1d, 0x90, 0xb4, 0x7d, 0x88, 0x90,
	0xff, 0xff, 0x24, 0x36, 0x95, 0xc8, 0x0d, 0x90, 0x3c, 0x86, 0x08, 0xd9, 0x93, 0x3a, 0x25, 0x78,
	0x9b, 0x80, 0x25, 0x5f, 0x15, 0xab, 0x2a, 0xbd, 0xbd, 0xd2, 0xbf, 0x7c, 0xa2, 0x9f, 0x03, 0x8b,
	0x05, 0xc6, 0x89, 0x1c, 0xb0, 0x5d, 0x90, 0xfd, 0xd6, 0x59, 0xa9, 0x52, 0x82, 0x16, 0xe6, 0x2e,
	0xb6, 0x0c, 0x2e, 0xff, 0x57, 0x24, 0xd5, 0x49, 0xbd, 0xda, 0x5c, 0xdb, 0x35, 0xc1, 0xc3, 0xdc,
	0xc5, 0x17, 0x70, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x05, 0x3f, 0xbb, 0x6a, 0x01, 0x00,
	0x00,
}
