// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/probes/http/proto/config.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProbeConf_ProtocolType int32

const (
	ProbeConf_HTTP  ProbeConf_ProtocolType = 0
	ProbeConf_HTTPS ProbeConf_ProtocolType = 1
)

var ProbeConf_ProtocolType_name = map[int32]string{
	0: "HTTP",
	1: "HTTPS",
}

var ProbeConf_ProtocolType_value = map[string]int32{
	"HTTP":  0,
	"HTTPS": 1,
}

func (x ProbeConf_ProtocolType) Enum() *ProbeConf_ProtocolType {
	p := new(ProbeConf_ProtocolType)
	*p = x
	return p
}

func (x ProbeConf_ProtocolType) String() string {
	return proto.EnumName(ProbeConf_ProtocolType_name, int32(x))
}

func (x *ProbeConf_ProtocolType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProbeConf_ProtocolType_value, data, "ProbeConf_ProtocolType")
	if err != nil {
		return err
	}
	*x = ProbeConf_ProtocolType(value)
	return nil
}

func (ProbeConf_ProtocolType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f0f7231b8fe2128, []int{0, 0}
}

type ProbeConf_Method int32

const (
	ProbeConf_GET     ProbeConf_Method = 0
	ProbeConf_POST    ProbeConf_Method = 1
	ProbeConf_PUT     ProbeConf_Method = 2
	ProbeConf_HEAD    ProbeConf_Method = 3
	ProbeConf_DELETE  ProbeConf_Method = 4
	ProbeConf_PATCH   ProbeConf_Method = 5
	ProbeConf_OPTIONS ProbeConf_Method = 6
)

var ProbeConf_Method_name = map[int32]string{
	0: "GET",
	1: "POST",
	2: "PUT",
	3: "HEAD",
	4: "DELETE",
	5: "PATCH",
	6: "OPTIONS",
}

var ProbeConf_Method_value = map[string]int32{
	"GET":     0,
	"POST":    1,
	"PUT":     2,
	"HEAD":    3,
	"DELETE":  4,
	"PATCH":   5,
	"OPTIONS": 6,
}

func (x ProbeConf_Method) Enum() *ProbeConf_Method {
	p := new(ProbeConf_Method)
	*p = x
	return p
}

func (x ProbeConf_Method) String() string {
	return proto.EnumName(ProbeConf_Method_name, int32(x))
}

func (x *ProbeConf_Method) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProbeConf_Method_value, data, "ProbeConf_Method")
	if err != nil {
		return err
	}
	*x = ProbeConf_Method(value)
	return nil
}

func (ProbeConf_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f0f7231b8fe2128, []int{0, 1}
}

// Next tag: 15
type ProbeConf struct {
	// Which HTTP protocol to use
	Protocol *ProbeConf_ProtocolType `protobuf:"varint,1,opt,name=protocol,enum=cloudprober.probes.http.ProbeConf_ProtocolType,def=0" json:"protocol,omitempty"`
	// Relative URL (to append to all targets). Must begin with '/'
	RelativeUrl *string `protobuf:"bytes,2,opt,name=relative_url,json=relativeUrl" json:"relative_url,omitempty"`
	// Port for HTTP requests. If not specfied, port is selected in the following
	// order:
	//  - If port is provided by the targets (e.g. kubernetes endpoint or
	//    service), that port is used.
	//  - 80 for HTTP and 443 for HTTPS.
	Port *int32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	// Whether to resolve the target before making the request. If set to false,
	// we hand over the target and relative_url directly to the golang's HTTP
	// module, Otherwise, we resolve the target first to an IP address and
	// make a request using that while passing target name as Host header.
	ResolveFirst *bool `protobuf:"varint,4,opt,name=resolve_first,json=resolveFirst,def=0" json:"resolve_first,omitempty"`
	// Export response (body) count as a metric
	ExportResponseAsMetrics *bool `protobuf:"varint,5,opt,name=export_response_as_metrics,json=exportResponseAsMetrics,def=0" json:"export_response_as_metrics,omitempty"`
	// HTTP request method
	Method *ProbeConf_Method `protobuf:"varint,7,opt,name=method,enum=cloudprober.probes.http.ProbeConf_Method,def=0" json:"method,omitempty"`
	// HTTP request headers
	Headers []*ProbeConf_Header `protobuf:"bytes,8,rep,name=headers" json:"headers,omitempty"`
	// Request body.
	Body *string `protobuf:"bytes,9,opt,name=body" json:"body,omitempty"`
	// Enable HTTP keep-alive. If set to true, underlying connection is reused
	// for further probes. Default is to close the connection after every request.
	KeepAlive *bool `protobuf:"varint,12,opt,name=keep_alive,json=keepAlive" json:"keep_alive,omitempty"`
	// Disable HTTP2
	// Golang HTTP client automatically enables HTTP/2 if server supports it. This
	// option disables that behavior to enforce HTTP/1.1 for testing purpose.
	DisableHttp2 *bool `protobuf:"varint,13,opt,name=disable_http2,json=disableHttp2" json:"disable_http2,omitempty"`
	// Disable TLS certificate validation. If set to true, any certificate
	// presented by the server for any host name will be accepted.
	DisableCertValidation *bool `protobuf:"varint,14,opt,name=disable_cert_validation,json=disableCertValidation" json:"disable_cert_validation,omitempty"`
	// Requests per probe.
	// Number of HTTP requests per probe. Requests are executed concurrently and
	// each HTTP re contributes to probe results. For example, if you run two
	// requests per probe, "total" counter will be incremented by 2.
	RequestsPerProbe *int32 `protobuf:"varint,98,opt,name=requests_per_probe,json=requestsPerProbe,def=1" json:"requests_per_probe,omitempty"`
	// How long to wait between two requests to the same target
	// NOTE: This field is now deprecated and will be removed after the v0.10.3
	// releases.
	RequestsIntervalMsec *int32   `protobuf:"varint,99,opt,name=requests_interval_msec,json=requestsIntervalMsec,def=25" json:"requests_interval_msec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeConf) Reset()         { *m = ProbeConf{} }
func (m *ProbeConf) String() string { return proto.CompactTextString(m) }
func (*ProbeConf) ProtoMessage()    {}
func (*ProbeConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f7231b8fe2128, []int{0}
}

func (m *ProbeConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeConf.Unmarshal(m, b)
}
func (m *ProbeConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeConf.Marshal(b, m, deterministic)
}
func (m *ProbeConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeConf.Merge(m, src)
}
func (m *ProbeConf) XXX_Size() int {
	return xxx_messageInfo_ProbeConf.Size(m)
}
func (m *ProbeConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeConf.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeConf proto.InternalMessageInfo

const Default_ProbeConf_Protocol ProbeConf_ProtocolType = ProbeConf_HTTP
const Default_ProbeConf_ResolveFirst bool = false
const Default_ProbeConf_ExportResponseAsMetrics bool = false
const Default_ProbeConf_Method ProbeConf_Method = ProbeConf_GET
const Default_ProbeConf_RequestsPerProbe int32 = 1
const Default_ProbeConf_RequestsIntervalMsec int32 = 25

func (m *ProbeConf) GetProtocol() ProbeConf_ProtocolType {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return Default_ProbeConf_Protocol
}

func (m *ProbeConf) GetRelativeUrl() string {
	if m != nil && m.RelativeUrl != nil {
		return *m.RelativeUrl
	}
	return ""
}

func (m *ProbeConf) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *ProbeConf) GetResolveFirst() bool {
	if m != nil && m.ResolveFirst != nil {
		return *m.ResolveFirst
	}
	return Default_ProbeConf_ResolveFirst
}

func (m *ProbeConf) GetExportResponseAsMetrics() bool {
	if m != nil && m.ExportResponseAsMetrics != nil {
		return *m.ExportResponseAsMetrics
	}
	return Default_ProbeConf_ExportResponseAsMetrics
}

func (m *ProbeConf) GetMethod() ProbeConf_Method {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return Default_ProbeConf_Method
}

func (m *ProbeConf) GetHeaders() []*ProbeConf_Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *ProbeConf) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *ProbeConf) GetKeepAlive() bool {
	if m != nil && m.KeepAlive != nil {
		return *m.KeepAlive
	}
	return false
}

func (m *ProbeConf) GetDisableHttp2() bool {
	if m != nil && m.DisableHttp2 != nil {
		return *m.DisableHttp2
	}
	return false
}

func (m *ProbeConf) GetDisableCertValidation() bool {
	if m != nil && m.DisableCertValidation != nil {
		return *m.DisableCertValidation
	}
	return false
}

func (m *ProbeConf) GetRequestsPerProbe() int32 {
	if m != nil && m.RequestsPerProbe != nil {
		return *m.RequestsPerProbe
	}
	return Default_ProbeConf_RequestsPerProbe
}

func (m *ProbeConf) GetRequestsIntervalMsec() int32 {
	if m != nil && m.RequestsIntervalMsec != nil {
		return *m.RequestsIntervalMsec
	}
	return Default_ProbeConf_RequestsIntervalMsec
}

type ProbeConf_Header struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeConf_Header) Reset()         { *m = ProbeConf_Header{} }
func (m *ProbeConf_Header) String() string { return proto.CompactTextString(m) }
func (*ProbeConf_Header) ProtoMessage()    {}
func (*ProbeConf_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f7231b8fe2128, []int{0, 0}
}

func (m *ProbeConf_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeConf_Header.Unmarshal(m, b)
}
func (m *ProbeConf_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeConf_Header.Marshal(b, m, deterministic)
}
func (m *ProbeConf_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeConf_Header.Merge(m, src)
}
func (m *ProbeConf_Header) XXX_Size() int {
	return xxx_messageInfo_ProbeConf_Header.Size(m)
}
func (m *ProbeConf_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeConf_Header.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeConf_Header proto.InternalMessageInfo

func (m *ProbeConf_Header) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProbeConf_Header) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("cloudprober.probes.http.ProbeConf_ProtocolType", ProbeConf_ProtocolType_name, ProbeConf_ProtocolType_value)
	proto.RegisterEnum("cloudprober.probes.http.ProbeConf_Method", ProbeConf_Method_name, ProbeConf_Method_value)
	proto.RegisterType((*ProbeConf)(nil), "cloudprober.probes.http.ProbeConf")
	proto.RegisterType((*ProbeConf_Header)(nil), "cloudprober.probes.http.ProbeConf.Header")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/probes/http/proto/config.proto", fileDescriptor_4f0f7231b8fe2128)
}

var fileDescriptor_4f0f7231b8fe2128 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x5d, 0x6b, 0xdb, 0x3c,
	0x14, 0xc7, 0xeb, 0xe6, 0xfd, 0x34, 0x2d, 0x46, 0xf4, 0x79, 0x2a, 0x0a, 0x83, 0xac, 0xbd, 0xc9,
	0x76, 0x61, 0xb3, 0xc0, 0xc6, 0x08, 0xbb, 0xc9, 0xd2, 0x74, 0x29, 0xac, 0xab, 0xa7, 0xba, 0xbb,
	0x35, 0x8e, 0x7d, 0x92, 0x98, 0x29, 0x96, 0x27, 0x29, 0x66, 0xfd, 0x6a, 0xfb, 0x74, 0x43, 0xb2,
	0x13, 0x72, 0x33, 0xe8, 0x95, 0x8e, 0xfe, 0xe7, 0xf7, 0x3f, 0x70, 0x5e, 0xe0, 0xd3, 0x2a, 0xd3,
	0xeb, 0xed, 0xc2, 0x4b, 0xc4, 0xc6, 0x5f, 0x09, 0xb1, 0xe2, 0xe8, 0x27, 0x5c, 0x6c, 0xd3, 0x42,
	0x8a, 0x05, 0x4a, 0xdf, 0x3e, 0xca, 0x5f, 0x6b, 0x5d, 0x98, 0x58, 0x0b, 0x3f, 0x11, 0xf9, 0x32,
	0x5b, 0x79, 0xf6, 0x43, 0x2e, 0x0e, 0x58, 0xaf, 0x62, 0x3d, 0xc3, 0x5e, 0xfd, 0x69, 0x43, 0x2f,
	0x30, 0xff, 0xa9, 0xc8, 0x97, 0xe4, 0x3b, 0x74, 0x2d, 0x9f, 0x08, 0x4e, 0x9d, 0x81, 0x33, 0x3c,
	0x1b, 0xf9, 0xde, 0x3f, 0x9c, 0xde, 0xde, 0x65, 0x22, 0x6b, 0x09, 0x9f, 0x0b, 0x1c, 0x37, 0xe7,
	0x61, 0x18, 0xb0, 0x7d, 0x19, 0xf2, 0x1a, 0xfa, 0x12, 0x79, 0xac, 0xb3, 0x12, 0xa3, 0xad, 0xe4,
	0xf4, 0x78, 0xe0, 0x0c, 0x7b, 0xec, 0x64, 0xa7, 0x3d, 0x49, 0x4e, 0x08, 0x34, 0x0b, 0x21, 0x35,
	0x6d, 0x0c, 0x9c, 0x61, 0x8b, 0xd9, 0x98, 0xbc, 0x85, 0x53, 0x89, 0x4a, 0xf0, 0x12, 0xa3, 0x65,
	0x26, 0x95, 0xa6, 0xcd, 0x81, 0x33, 0xec, 0x8e, 0x5b, 0xcb, 0x98, 0x2b, 0x64, 0xfd, 0x3a, 0x77,
	0x6b, 0x52, 0xe4, 0x33, 0x5c, 0xe2, 0x6f, 0xe3, 0x8a, 0x24, 0xaa, 0x42, 0xe4, 0x0a, 0xa3, 0x58,
	0x45, 0x1b, 0xd4, 0x32, 0x4b, 0x14, 0x6d, 0x1d, 0x1a, 0x2f, 0x2a, 0x90, 0xd5, 0xdc, 0x44, 0xdd,
	0x57, 0x14, 0xb9, 0x85, 0xf6, 0x06, 0xf5, 0x5a, 0xa4, 0xb4, 0x63, 0xfb, 0x7e, 0xf3, 0x82, 0xbe,
	0xef, 0xad, 0x61, 0xdc, 0xf8, 0x32, 0x0b, 0x59, 0xed, 0x26, 0x53, 0xe8, 0xac, 0x31, 0x4e, 0x51,
	0x2a, 0xda, 0x1d, 0x34, 0x86, 0x27, 0x2f, 0x2a, 0x34, 0xb7, 0x0e, 0xb6, 0x73, 0x9a, 0x81, 0x2c,
	0x44, 0xfa, 0x4c, 0x7b, 0x76, 0x56, 0x36, 0x26, 0xaf, 0x00, 0x7e, 0x22, 0x16, 0x51, 0xcc, 0xb3,
	0x12, 0x69, 0xdf, 0x34, 0xc5, 0x7a, 0x46, 0x99, 0x18, 0x81, 0x5c, 0xc3, 0x69, 0x9a, 0xa9, 0x78,
	0xc1, 0x31, 0x32, 0xc5, 0x47, 0xf4, 0xd4, 0x12, 0xfd, 0x5a, 0x9c, 0x1b, 0x8d, 0x7c, 0x80, 0x8b,
	0x1d, 0x94, 0xa0, 0xd4, 0x51, 0x19, 0xf3, 0x2c, 0x8d, 0x75, 0x26, 0x72, 0x7a, 0x66, 0xf1, 0xff,
	0xea, 0xf4, 0x14, 0xa5, 0xfe, 0xb1, 0x4f, 0x12, 0x1f, 0x88, 0xc4, 0x5f, 0x5b, 0x54, 0x5a, 0x45,
	0x05, 0xca, 0xc8, 0x76, 0x41, 0x17, 0x66, 0x5d, 0x63, 0xe7, 0x1d, 0x73, 0x77, 0xc9, 0x00, 0xa5,
	0x6d, 0x8a, 0x7c, 0x84, 0xff, 0xf7, 0x86, 0x2c, 0xd7, 0x28, 0xcb, 0x98, 0x47, 0x1b, 0x85, 0x09,
	0x4d, 0xac, 0xe9, 0x78, 0xf4, 0x9e, 0x9d, 0xef, 0x88, 0xbb, 0x1a, 0xb8, 0x57, 0x98, 0x5c, 0x8e,
	0xa0, 0x5d, 0x4d, 0xc3, 0x0c, 0x21, 0x8f, 0x37, 0x68, 0xef, 0xb0, 0xc7, 0x6c, 0x4c, 0xce, 0xa1,
	0x55, 0xc6, 0x7c, 0x8b, 0xf5, 0x15, 0x55, 0x9f, 0xab, 0x6b, 0xe8, 0x1f, 0x9e, 0x20, 0xe9, 0x82,
	0x3d, 0x42, 0xf7, 0x88, 0xf4, 0xa0, 0x65, 0xa2, 0x47, 0xd7, 0xb9, 0x62, 0xd0, 0xae, 0xf6, 0x45,
	0x3a, 0x60, 0x36, 0xe6, 0x1e, 0x19, 0x2e, 0x78, 0x78, 0x0c, 0x5d, 0xc7, 0x48, 0xc1, 0x53, 0xe8,
	0x1e, 0x5b, 0xeb, 0x6c, 0x72, 0xe3, 0x36, 0x08, 0x40, 0xfb, 0x66, 0xf6, 0x75, 0x16, 0xce, 0xdc,
	0xa6, 0x29, 0x13, 0x4c, 0xc2, 0xe9, 0xdc, 0x6d, 0x91, 0x13, 0xe8, 0x3c, 0x04, 0xe1, 0xdd, 0xc3,
	0xb7, 0x47, 0xb7, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x4c, 0x07, 0x7a, 0x94, 0x03, 0x00,
	0x00,
}
