// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/google/cloudprober/surfacers/prometheus/config.proto

/*
Package prometheus is a generated protocol buffer package.

It is generated from these files:
	github.com/google/cloudprober/surfacers/prometheus/config.proto

It has these top-level messages:
	SurfacerConf
*/
package prometheus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SurfacerConf struct {
	// How many metrics entries (EventMetrics) to buffer. Incoming metrics
	// processing is paused while serving data to prometheus. This buffer is to
	// make writes to prometheus surfacer non-blocking.
	MetricsBufferSize *int64 `protobuf:"varint,1,opt,name=metrics_buffer_size,json=metricsBufferSize,def=10000" json:"metrics_buffer_size,omitempty"`
	// HTTP server port that prometheus surfacer listens on.
	Port *int32 `protobuf:"varint,2,opt,name=port,def=9313" json:"port,omitempty"`
	// URL that prometheus scrapes metrics from.
	MetricsUrl       *string `protobuf:"bytes,3,opt,name=metrics_url,json=metricsUrl,def=/metrics" json:"metrics_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SurfacerConf) Reset()                    { *m = SurfacerConf{} }
func (m *SurfacerConf) String() string            { return proto.CompactTextString(m) }
func (*SurfacerConf) ProtoMessage()               {}
func (*SurfacerConf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_SurfacerConf_MetricsBufferSize int64 = 10000
const Default_SurfacerConf_Port int32 = 9313
const Default_SurfacerConf_MetricsUrl string = "/metrics"

func (m *SurfacerConf) GetMetricsBufferSize() int64 {
	if m != nil && m.MetricsBufferSize != nil {
		return *m.MetricsBufferSize
	}
	return Default_SurfacerConf_MetricsBufferSize
}

func (m *SurfacerConf) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return Default_SurfacerConf_Port
}

func (m *SurfacerConf) GetMetricsUrl() string {
	if m != nil && m.MetricsUrl != nil {
		return *m.MetricsUrl
	}
	return Default_SurfacerConf_MetricsUrl
}

func init() {
	proto.RegisterType((*SurfacerConf)(nil), "cloudprober.surfacer.prometheus.SurfacerConf")
}

func init() {
	proto.RegisterFile("github.com/google/cloudprober/surfacers/prometheus/config.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcc, 0x31, 0x4b, 0x03, 0x31,
	0x18, 0xc6, 0x71, 0x62, 0x5b, 0xd0, 0xe8, 0x62, 0x5c, 0xb2, 0x79, 0x38, 0x9d, 0x4b, 0x92, 0x52,
	0x1c, 0xbc, 0x45, 0xd0, 0x6f, 0x70, 0xc5, 0xb9, 0x78, 0xf1, 0x4d, 0x1a, 0xc8, 0xf5, 0x0d, 0x6f,
	0x92, 0xa5, 0x1f, 0xc1, 0x4f, 0x2d, 0x94, 0x1c, 0xba, 0x3d, 0xfc, 0xf9, 0xf1, 0xf0, 0x37, 0x1f,
	0xca, 0xb1, 0x4e, 0xca, 0xe2, 0xac, 0x3d, 0xa2, 0x8f, 0xa0, 0x6d, 0xc4, 0xfa, 0x9d, 0x08, 0x27,
	0x20, 0x9d, 0x2b, 0xb9, 0x2f, 0x0b, 0x94, 0x75, 0x22, 0x9c, 0xa1, 0x1c, 0xa1, 0x66, 0x6d, 0xf1,
	0xe4, 0x82, 0x57, 0x89, 0xb0, 0xa0, 0x78, 0xfc, 0xc7, 0xd5, 0xc2, 0xd5, 0x9f, 0x7e, 0xfa, 0x61,
	0xfc, 0x6e, 0xdf, 0xfa, 0x07, 0x9e, 0x9c, 0x78, 0xe1, 0x0f, 0x33, 0x14, 0x0a, 0x36, 0x1f, 0xa6,
	0xea, 0x1c, 0xd0, 0x21, 0x87, 0x33, 0x48, 0xd6, 0xb1, 0x7e, 0x35, 0x6c, 0xb6, 0xc6, 0x18, 0x33,
	0xde, 0x37, 0xf1, 0x7e, 0x01, 0xfb, 0x70, 0x06, 0x21, 0xf9, 0x3a, 0x21, 0x15, 0x79, 0xd5, 0xb1,
	0x7e, 0x33, 0xac, 0x5f, 0x77, 0xdb, 0xdd, 0x78, 0x29, 0xe2, 0x99, 0xdf, 0x2e, 0x87, 0x95, 0xa2,
	0x5c, 0x75, 0xac, 0xbf, 0x19, 0xae, 0x75, 0x6b, 0x23, 0x6f, 0xe3, 0x93, 0xe2, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x69, 0x3e, 0xe1, 0x47, 0xef, 0x00, 0x00, 0x00,
}
